"""
Tasks Router — The execution layer of the relationship system.
Campaigns = strategy, Tasks = execution, Events = history.

Tasks come from 3 sources:
1. Campaign steps (auto-generated by scheduler when step date arrives)
2. Date triggers (birthdays, anniversaries, holidays — auto-generated)
3. Manual (user creates follow-up reminders on a contact)
Plus system-generated tasks for dormant contacts.
"""
from fastapi import APIRouter, HTTPException
from bson import ObjectId
from datetime import datetime, timezone, timedelta
from typing import Optional
import logging

from routers.database import get_db, get_user_by_id

router = APIRouter(prefix="/tasks", tags=["Tasks"])
logger = logging.getLogger(__name__)

PRIORITY_ORDER = {"high": 1, "medium": 2, "low": 3}


def _serialize(task: dict) -> dict:
    """Serialize a task for JSON response."""
    task["_id"] = str(task["_id"])
    for key in ("due_date", "created_at", "completed_at", "snoozed_until"):
        val = task.get(key)
        if isinstance(val, datetime):
            task[key] = val.isoformat()
    for key in ("contact_id", "campaign_id"):
        if isinstance(task.get(key), ObjectId):
            task[key] = str(task[key])
    # Legacy compat: map completed bool → status
    if task.get("completed") and task.get("status") != "completed":
        task["status"] = "completed"
    if not task.get("status"):
        task["status"] = "pending"
    return task


@router.get("/{user_id}")
async def get_tasks(user_id: str, filter: str = "today", limit: int = 50, skip: int = 0):
    """
    Get tasks. Filters: today (due today + overdue), overdue, upcoming, completed, all
    """
    db = get_db()
    now = datetime.now(timezone.utc)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    today_end = today_start + timedelta(days=1)

    base = {"user_id": user_id}

    if filter == "today":
        base["status"] = {"$in": ["pending", "snoozed", None]}
        base["$or"] = [
            {"due_date": {"$lte": today_end}},
            {"due_date": {"$exists": False}},
            {"due_date": None},
        ]
    elif filter == "overdue":
        base["status"] = {"$in": ["pending", None]}
        base["due_date"] = {"$lt": today_start}
    elif filter == "upcoming":
        base["status"] = {"$in": ["pending", "snoozed", None]}
        base["due_date"] = {"$gt": today_end}
    elif filter == "completed":
        base["$or"] = [{"status": "completed"}, {"completed": True}]
    # else: "all" — no status filter

    tasks = await db.tasks.find(base).sort([
        ("priority_order", 1),
        ("due_date", 1),
        ("created_at", -1),
    ]).skip(skip).limit(limit).to_list(limit)

    # Post-filter snoozed tasks not yet due
    result = []
    for t in tasks:
        snoozed_until = t.get("snoozed_until")
        if t.get("status") == "snoozed" and snoozed_until and isinstance(snoozed_until, datetime):
            if snoozed_until.replace(tzinfo=timezone.utc if snoozed_until.tzinfo is None else snoozed_until.tzinfo) > now:
                continue
        result.append(_serialize(t))

    return result


@router.get("/{user_id}/summary")
async def get_task_summary(user_id: str):
    """Daily summary for scoreboard + progress bar."""
    db = get_db()
    now = datetime.now(timezone.utc)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    today_end = today_start + timedelta(days=1)

    total_today = await db.tasks.count_documents({
        "user_id": user_id,
        "$or": [
            {"due_date": {"$lte": today_end}},
            {"due_date": {"$exists": False}},
            {"due_date": None},
        ],
        "status": {"$nin": ["dismissed"]},
    })

    completed_today = await db.tasks.count_documents({
        "user_id": user_id,
        "$or": [
            {"status": "completed", "completed_at": {"$gte": today_start, "$lt": today_end}},
            {"completed": True, "created_at": {"$gte": today_start, "$lt": today_end}},
        ],
    })

    pending = await db.tasks.count_documents({
        "user_id": user_id,
        "status": {"$in": ["pending", "snoozed", None]},
        "$or": [
            {"due_date": {"$lte": today_end}},
            {"due_date": {"$exists": False}},
            {"due_date": None},
        ],
    })

    overdue = await db.tasks.count_documents({
        "user_id": user_id,
        "status": {"$in": ["pending", None]},
        "completed": {"$ne": True},
        "due_date": {"$lt": today_start},
    })

    # Today's activity from contact_events
    activity = {}
    try:
        pipeline = [
            {"$match": {"user_id": user_id, "timestamp": {"$gte": today_start, "$lt": today_end}}},
            {"$group": {"_id": "$event_type", "count": {"$sum": 1}}},
        ]
        for r in await db.contact_events.aggregate(pipeline).to_list(50):
            activity[r["_id"]] = r["count"]
    except Exception:
        pass

    return {
        "total_today": total_today,
        "completed_today": completed_today,
        "pending_today": pending,
        "overdue": overdue,
        "progress_pct": round((completed_today / max(total_today, 1)) * 100),
        "activity": {
            "calls": activity.get("call_placed", 0) + activity.get("call_received", 0),
            "texts": activity.get("sms_sent", 0),
            "emails": activity.get("email_sent", 0),
            "cards": sum(v for k, v in activity.items() if "card" in k),
            "reviews": activity.get("review_invite_sent", 0) + activity.get("review_shared", 0),
        },
    }


@router.post("/{user_id}")
async def create_task(user_id: str, task_data: dict):
    """Create a manual task. Required: title. Optional: contact_id, description, due_date, etc."""
    db = get_db()
    title = (task_data.get("title") or "").strip()
    if not title:
        raise HTTPException(status_code=400, detail="Title is required")

    contact_id = task_data.get("contact_id", "")
    contact_name = task_data.get("contact_name", "")
    contact_phone = task_data.get("contact_phone", "")

    if contact_id and not contact_name:
        try:
            c = await db.contacts.find_one({"_id": ObjectId(contact_id)})
            if c:
                contact_name = f"{c.get('first_name','')} {c.get('last_name','')}".strip()
                contact_phone = c.get("phone", "")
        except Exception:
            pass

    due_date = None
    if task_data.get("due_date"):
        try:
            due_date = datetime.fromisoformat(str(task_data["due_date"]).replace("Z", "+00:00"))
        except Exception:
            due_date = datetime.now(timezone.utc)
    else:
        due_date = datetime.now(timezone.utc)

    priority = task_data.get("priority", "medium")

    task = {
        "user_id": user_id,
        "contact_id": contact_id,
        "contact_name": contact_name,
        "contact_phone": contact_phone,
        "type": task_data.get("type", "manual"),
        "source": "manual",
        "title": title,
        "description": task_data.get("description", ""),
        "suggested_message": task_data.get("suggested_message", ""),
        "action_type": task_data.get("action_type", "manual"),
        "priority": priority,
        "priority_order": PRIORITY_ORDER.get(priority, 2),
        "status": "pending",
        "completed": False,
        "due_date": due_date,
        "completed_at": None,
        "snoozed_until": None,
        "campaign_id": None,
        "campaign_name": None,
        "pending_send_id": None,
        "channel": task_data.get("channel", ""),
        "created_at": datetime.now(timezone.utc),
    }

    result = await db.tasks.insert_one(task)
    task["_id"] = str(result.inserted_id)
    logger.info(f"Manual task created: '{title}' for user {user_id}")
    return _serialize(task)


@router.patch("/{user_id}/{task_id}")
async def update_task(user_id: str, task_id: str, update_data: dict):
    """Update a task: complete, snooze, dismiss, or edit fields."""
    db = get_db()
    task = await db.tasks.find_one({"_id": ObjectId(task_id), "user_id": user_id})
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    action = update_data.get("action", "edit")
    updates = {}

    if action == "complete":
        updates["status"] = "completed"
        updates["completed"] = True
        updates["completed_at"] = datetime.now(timezone.utc)
        # Log completion event
        cid = task.get("contact_id", "")
        if cid:
            try:
                user = await get_user_by_id(user_id)
                await db.contact_events.insert_one({
                    "event_type": "task_completed",
                    "title": f"Task Completed: {task.get('title', '')}",
                    "user_id": user_id,
                    "contact_id": cid,
                    "org_id": (user or {}).get("organization_id", ""),
                    "description": task.get("description", ""),
                    "timestamp": datetime.now(timezone.utc),
                    "source": task.get("source", "manual"),
                })
            except Exception as e:
                logger.error(f"Failed to log task completion: {e}")

    elif action == "snooze":
        hours = update_data.get("snooze_hours", 24)
        snooze_until = datetime.now(timezone.utc) + timedelta(hours=hours)
        updates["status"] = "snoozed"
        updates["snoozed_until"] = snooze_until
        updates["due_date"] = snooze_until

    elif action == "dismiss":
        updates["status"] = "dismissed"

    elif action == "edit":
        for f in ("title", "description", "priority", "action_type", "suggested_message"):
            if f in update_data:
                updates[f] = update_data[f]
                if f == "priority":
                    updates["priority_order"] = PRIORITY_ORDER.get(update_data[f], 2)
        if "due_date" in update_data:
            try:
                updates["due_date"] = datetime.fromisoformat(str(update_data["due_date"]).replace("Z", "+00:00"))
            except Exception:
                pass

    if updates:
        await db.tasks.update_one({"_id": ObjectId(task_id)}, {"$set": updates})

    updated = await db.tasks.find_one({"_id": ObjectId(task_id)})
    return _serialize(updated)


# Keep legacy PUT for backward compat
@router.put("/{user_id}/{task_id}")
async def update_task_legacy(user_id: str, task_id: str, task_data: dict):
    """Legacy update endpoint."""
    db = get_db()
    allowed = ["completed", "title", "description", "due_date", "type", "priority", "status"]
    update_dict = {k: v for k, v in task_data.items() if k in allowed}
    if "completed" in update_dict and update_dict["completed"]:
        update_dict["status"] = "completed"
        update_dict["completed_at"] = datetime.now(timezone.utc)
    update_dict["updated_at"] = datetime.now(timezone.utc)

    result = await db.tasks.update_one(
        {"_id": ObjectId(task_id), "user_id": user_id},
        {"$set": update_dict}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Task not found")
    return {"message": "Task updated successfully"}


@router.delete("/{user_id}/{task_id}")
async def delete_task(user_id: str, task_id: str):
    """Delete a task."""
    result = await get_db().tasks.delete_one({"_id": ObjectId(task_id), "user_id": user_id})
    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Task not found")
    return {"success": True}


@router.get("/{user_id}/performance")
async def get_performance(user_id: str, period: str = "week"):
    """Performance stats for My Performance page. period: today, week, month"""
    db = get_db()
    now = datetime.now(timezone.utc)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)

    if period == "today":
        start = today_start
    elif period == "month":
        start = today_start - timedelta(days=30)
    else:
        start = today_start - timedelta(days=7)

    match = {"user_id": user_id, "timestamp": {"$gte": start, "$lt": now}}

    # Aggregate events by type
    pipeline = [
        {"$match": match},
        {"$group": {"_id": "$event_type", "count": {"$sum": 1}}},
    ]
    activity = {}
    for r in await db.contact_events.aggregate(pipeline).to_list(100):
        activity[r["_id"]] = r["count"]

    # Previous period for trend
    prev_start = start - (now - start)
    prev_match = {"user_id": user_id, "timestamp": {"$gte": prev_start, "$lt": start}}
    prev_total = await db.contact_events.count_documents(prev_match)
    curr_total = await db.contact_events.count_documents(match)
    trend_pct = round(((curr_total - prev_total) / max(prev_total, 1)) * 100) if prev_total else 0

    # New contacts added
    new_leads = await db.contacts.count_documents({
        "$or": [{"user_id": user_id}, {"created_by": user_id}],
        "created_at": {"$gte": start, "$lt": now},
    })

    return {
        "total_touchpoints": curr_total,
        "trend_pct": trend_pct,
        "communication": {
            "texts": activity.get("sms_sent", 0),
            "emails": activity.get("email_sent", 0),
            "calls": activity.get("call_placed", 0) + activity.get("call_received", 0),
        },
        "sharing": {
            "cards": sum(v for k, v in activity.items() if "card_shared" in k or "card_sent" in k or "digital_card" in k),
            "reviews": activity.get("review_invite_sent", 0) + activity.get("review_shared", 0) + activity.get("review_request_sent", 0),
            "congrats": sum(v for k, v in activity.items() if "congrats" in k or "birthday_card" in k or "holiday_card" in k or "welcome_card" in k or "anniversary_card" in k or "thankyou_card" in k or "thank_you_card" in k),
        },
        "engagement": {
            "link_clicks": activity.get("link_clicked", 0) + activity.get("card_viewed", 0),
            "email_opens": activity.get("email_opened", 0),
            "replies": activity.get("reply_received", 0) + activity.get("sms_received", 0),
            "new_leads": new_leads,
        },
        "click_through": {
            "digital_card_views": activity.get("digital_card_viewed", 0) + activity.get("card_viewed", 0),
            "review_link_clicks": activity.get("review_link_clicked", 0),
            "showcase_views": activity.get("showcase_viewed", 0) + activity.get("showroom_viewed", 0),
            "link_page_visits": activity.get("link_page_viewed", 0),
        },
    }


@router.post("/{user_id}/generate-system-tasks")
async def generate_system_tasks(user_id: str):
    """
    Generate system tasks: dormant contacts (90+ days), upcoming birthdays, purchase anniversaries.
    Uses idempotency keys to prevent duplicates.
    """
    db = get_db()
    now = datetime.now(timezone.utc)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    created = 0

    user = await get_user_by_id(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    from routers.database import get_data_filter
    base_filter = await get_data_filter(user_id)

    # === DORMANT CONTACTS (no event in 90+ days) ===
    cutoff = now - timedelta(days=90)
    contacts = await db.contacts.find({
        **base_filter,
        "phone": {"$exists": True, "$ne": ""},
    }).to_list(500)

    for contact in contacts:
        cid = str(contact["_id"])
        name = f"{contact.get('first_name','')} {contact.get('last_name','')}".strip()
        if not name:
            continue

        last = await db.contact_events.find_one(
            {"contact_id": cid, "user_id": user_id},
            sort=[("timestamp", -1)]
        )
        last_ts = (last or {}).get("timestamp") or contact.get("created_at")
        if not last_ts or not isinstance(last_ts, datetime):
            continue

        if last_ts.tzinfo is None:
            last_ts = last_ts.replace(tzinfo=timezone.utc)
        if last_ts < cutoff:
            idem = f"dormant_{user_id}_{cid}_{today_start.strftime('%Y-%m-%d')}"
            if await db.tasks.find_one({"idempotency_key": idem}):
                continue
            days = (now - last_ts).days
            await db.tasks.insert_one({
                "user_id": user_id, "contact_id": cid,
                "contact_name": name, "contact_phone": contact.get("phone", ""),
                "type": "follow_up", "source": "system",
                "title": f"Reconnect with {name}",
                "description": f"It's been {days} days since your last interaction.",
                "suggested_message": f"Hey {contact.get('first_name','there')}! It's been a while — just wanted to check in and see how things are going!",
                "action_type": "text", "priority": "medium", "priority_order": 2,
                "status": "pending", "completed": False,
                "due_date": now, "channel": "sms",
                "created_at": now, "idempotency_key": idem,
            })
            created += 1

    # === UPCOMING BIRTHDAYS (next 3 days) ===
    bday_contacts = await db.contacts.find({
        **base_filter, "birthday": {"$exists": True, "$ne": None},
    }).to_list(500)

    for offset in range(4):
        check = now + timedelta(days=offset)
        cm, cd = check.month, check.day
        for contact in bday_contacts:
            bday = contact.get("birthday")
            if bday and isinstance(bday, datetime) and bday.month == cm and bday.day == cd:
                cid = str(contact["_id"])
                name = f"{contact.get('first_name','')} {contact.get('last_name','')}".strip()
                idem = f"birthday_{user_id}_{cid}_{check.strftime('%Y-%m-%d')}"
                if await db.tasks.find_one({"idempotency_key": idem}):
                    continue
                label = "today" if offset == 0 else f"in {offset} day{'s' if offset > 1 else ''}"
                await db.tasks.insert_one({
                    "user_id": user_id, "contact_id": cid,
                    "contact_name": name, "contact_phone": contact.get("phone", ""),
                    "type": "birthday", "source": "system",
                    "title": f"Birthday {label}: {name}",
                    "description": f"{name}'s birthday is {label}. Send a personal message!",
                    "suggested_message": f"Happy Birthday, {contact.get('first_name','')}! Hope you have an amazing day!",
                    "action_type": "text",
                    "priority": "high" if offset == 0 else "medium",
                    "priority_order": 1 if offset == 0 else 2,
                    "status": "pending", "completed": False,
                    "due_date": check.replace(hour=9, minute=0, second=0),
                    "channel": "sms", "created_at": now, "idempotency_key": idem,
                })
                created += 1

    # === PURCHASE ANNIVERSARIES (next 3 days) ===
    sold_contacts = await db.contacts.find({
        **base_filter,
        "$or": [
            {"date_sold": {"$exists": True, "$ne": None}},
            {"purchase_date": {"$exists": True, "$ne": None}},
        ],
    }).to_list(500)

    for offset in range(4):
        check = now + timedelta(days=offset)
        cm, cd = check.month, check.day
        for contact in sold_contacts:
            sd = contact.get("date_sold") or contact.get("purchase_date")
            if sd and isinstance(sd, datetime) and sd.month == cm and sd.day == cd and sd.year != check.year:
                cid = str(contact["_id"])
                name = f"{contact.get('first_name','')} {contact.get('last_name','')}".strip()
                years = check.year - sd.year
                idem = f"anniversary_{user_id}_{cid}_{check.strftime('%Y-%m-%d')}"
                if await db.tasks.find_one({"idempotency_key": idem}):
                    continue
                label = "today" if offset == 0 else f"in {offset} day{'s' if offset > 1 else ''}"
                await db.tasks.insert_one({
                    "user_id": user_id, "contact_id": cid,
                    "contact_name": name, "contact_phone": contact.get("phone", ""),
                    "type": "anniversary", "source": "system",
                    "title": f"{years}-Year Anniversary {label}: {name}",
                    "description": f"It's been {years} year{'s' if years>1 else ''} since {name}'s purchase.",
                    "suggested_message": f"Hey {contact.get('first_name','')}! Can you believe it's been {years} year{'s' if years>1 else ''} already? Hope everything's still going great!",
                    "action_type": "text",
                    "priority": "high" if offset == 0 else "medium",
                    "priority_order": 1 if offset == 0 else 2,
                    "status": "pending", "completed": False,
                    "due_date": check.replace(hour=9, minute=0, second=0),
                    "channel": "sms", "created_at": now, "idempotency_key": idem,
                })
                created += 1

    logger.info(f"System tasks generated for {user_id}: {created} new")
    return {"created": created, "user_id": user_id}
