"""
Tasks Router — The execution layer of the relationship system.
Campaigns = strategy, Tasks = execution, Events = history.

Tasks come from 3 sources:
1. Campaign steps (auto-generated by scheduler when step date arrives)
2. Date triggers (birthdays, anniversaries, holidays — auto-generated)
3. Manual (user creates follow-up reminders on a contact)
Plus system-generated tasks for dormant contacts.
"""
from fastapi import APIRouter, HTTPException
from bson import ObjectId
from datetime import datetime, timezone, timedelta
from typing import Optional
from zoneinfo import ZoneInfo
import logging

from routers.database import get_db, get_user_by_id

router = APIRouter(prefix="/tasks", tags=["Tasks"])
logger = logging.getLogger(__name__)


async def _catchup_overdue_campaign_tasks(user_id: str):
    """Create missing tasks for overdue campaign enrollments.
    This ensures campaign steps that the scheduler missed still appear in Today's Touchpoints.
    Checks both: 1) enrollments where next_send_at passed, and 2) steps marked 'pending' in messages_sent.
    """
    db = get_db()
    now = datetime.now(timezone.utc)

    try:
        # ── Path 1: Enrollments where next_send_at has passed ──
        overdue_enrollments = await db.campaign_enrollments.find({
            "user_id": user_id,
            "status": "active",
            "next_send_at": {"$lte": now},
        }).to_list(50)

        # ── Path 2: Enrollments with pending message steps (scheduler already advanced but task missing/dismissed) ──
        pending_step_enrollments = await db.campaign_enrollments.find({
            "user_id": user_id,
            "status": "active",
            "messages_sent.status": "pending",
        }).to_list(50)

        # Merge and deduplicate by enrollment _id
        seen_ids = set()
        all_enrollments = []
        for e in overdue_enrollments + pending_step_enrollments:
            eid = str(e["_id"])
            if eid not in seen_ids:
                seen_ids.add(eid)
                all_enrollments.append(e)

        created = 0
        for enrollment in all_enrollments:
            campaign_id = enrollment.get("campaign_id", "")
            contact_id = enrollment.get("contact_id", "")

            # Load campaign to get step details
            campaign = None
            try:
                campaign = await db.campaigns.find_one({"_id": ObjectId(campaign_id)})
            except Exception:
                pass
            if not campaign:
                continue

            sequences = campaign.get("sequences", [])
            if not sequences:
                continue

            # Determine which steps need tasks
            steps_to_process = []
            messages_sent = enrollment.get("messages_sent", [])

            # Check for pending steps in messages_sent
            for msg in messages_sent:
                if msg.get("status") == "pending":
                    steps_to_process.append(msg.get("step", 0))

            # Also check current step if next_send_at passed
            current_step = enrollment.get("current_step", 1)
            next_send_at = enrollment.get("next_send_at")
            if next_send_at and next_send_at <= now and current_step not in steps_to_process:
                steps_to_process.append(current_step)

            for step_num in steps_to_process:
                if step_num < 1 or step_num > len(sequences):
                    continue

                idem_key = f"campaign_{campaign_id}_{contact_id}_{step_num}"

                # Skip if a usable task already exists (pending or snoozed)
                existing = await db.tasks.find_one({"idempotency_key": idem_key})
                if existing:
                    ex_status = existing.get("status", "")
                    if ex_status in ("pending", "snoozed"):
                        continue  # Task exists and is active — no action needed
                    elif ex_status in ("dismissed",):
                        # Task was dismissed but step is still pending — recreate it
                        await db.tasks.delete_one({"_id": existing["_id"]})
                    else:
                        continue  # completed or other — skip

                step = sequences[step_num - 1]
                channel = step.get("channel", "sms")
                message_content = step.get("message_template", "") or step.get("message", "")
                contact_display = enrollment.get("contact_name", "contact")
                action_type = step.get("action_type", "message")

                if action_type == "send_card":
                    card_type = step.get("card_type", "congrats")
                    task_title = f"Send {card_type.title()} Card to {contact_display}"
                    task_desc = f"Campaign '{campaign.get('name', '')}' step {step_num}: Send a {card_type} card."
                else:
                    task_title = f"Send {channel.upper()} to {contact_display}"
                    task_desc = f"Campaign '{campaign.get('name', '')}' step {step_num}: {message_content[:200]}"

                # Check if pending_send exists, if not create one
                existing_ps = await db.campaign_pending_sends.find_one({
                    "campaign_id": campaign_id,
                    "contact_id": contact_id,
                    "step": step_num,
                    "status": "pending",
                })

                if existing_ps:
                    pending_send_id = str(existing_ps["_id"])
                else:
                    pending_result = await db.campaign_pending_sends.insert_one({
                        "user_id": user_id,
                        "campaign_id": campaign_id,
                        "campaign_name": campaign.get("name", ""),
                        "contact_id": contact_id,
                        "contact_name": enrollment.get("contact_name", ""),
                        "contact_phone": enrollment.get("contact_phone", ""),
                        "step": step_num,
                        "channel": channel,
                        "message": message_content,
                        "status": "pending",
                        "created_at": now,
                    })
                    pending_send_id = str(pending_result.inserted_id)

                # Replace template variables
                contact_first = enrollment.get("contact_name", "").split()[0] if enrollment.get("contact_name") else "there"
                contact_last = " ".join(enrollment.get("contact_name", "").split()[1:]) if enrollment.get("contact_name") else ""
                clean_message = message_content.replace("{name}", contact_first).replace("{first_name}", contact_first).replace("{last_name}", contact_last)
                
                # Replace {review_link} with sender's review URL
                if "{review_link}" in clean_message or "{review_url}" in clean_message:
                    user_doc = await db.users.find_one({"_id": ObjectId(user_id)})
                    review_url = (user_doc.get("review_url", "") or "") if user_doc else ""
                    if not review_url and user_doc:
                        store_id = user_doc.get("store_id")
                        if store_id:
                            store = await db.stores.find_one({"_id": ObjectId(store_id)})
                            if store:
                                rl = store.get("review_links", {})
                                review_url = rl.get("google", "") or rl.get("yelp", "") or ""
                    clean_message = clean_message.replace("{review_link}", review_url).replace("{review_url}", review_url)

                try:
                    await db.tasks.insert_one({
                        "user_id": user_id,
                        "contact_id": contact_id,
                        "contact_name": enrollment.get("contact_name", ""),
                        "contact_phone": enrollment.get("contact_phone", ""),
                        "type": "campaign_send",
                        "title": task_title,
                        "description": task_desc,
                        "suggested_message": clean_message,
                        "action_type": "card" if action_type == "send_card" else ("email" if channel == "email" else "text"),
                        "due_date": now,
                        "priority": "high",
                        "priority_order": 1,
                        "status": "pending",
                        "completed": False,
                        "source": "campaign",
                        "campaign_id": campaign_id,
                        "campaign_name": campaign.get("name", ""),
                        "pending_send_id": pending_send_id,
                        "channel": channel,
                        "created_at": now,
                        "idempotency_key": idem_key,
                    })
                    created += 1
                except Exception:
                    pass  # DuplicateKeyError or other - skip silently

        if created > 0:
            logger.info(f"[Tasks] Catch-up: created {created} missing campaign tasks for user {user_id}")
    except Exception as e:
        logger.warning(f"[Tasks] Catch-up check failed: {e}")


async def get_user_day_bounds(user_id: str, period: str = "today"):
    """
    Calculate the start/end of 'today', 'week', or 'month' in the user's local timezone,
    returned as UTC datetimes for MongoDB queries.
    
    Lookup order: user.timezone → store.timezone → UTC
    Uses IANA timezone names (e.g. America/Denver) which auto-handle DST.
    """
    db = get_db()
    tz_name = None
    
    # 1. Check user's timezone
    user = await db.users.find_one({"_id": ObjectId(user_id)}, {"timezone": 1, "store_id": 1})
    if user:
        user_tz = user.get("timezone")
        if user_tz and user_tz != "UTC":
            tz_name = user_tz
        
        # 2. Fallback to store timezone
        if not tz_name and user.get("store_id"):
            try:
                store = await db.stores.find_one(
                    {"_id": ObjectId(str(user["store_id"]))},
                    {"timezone": 1}
                )
                if store and store.get("timezone"):
                    tz_name = store["timezone"]
            except Exception:
                pass
    
    # 3. Final fallback to UTC
    try:
        local_tz = ZoneInfo(tz_name) if tz_name else timezone.utc
    except Exception:
        local_tz = timezone.utc
    
    # Get current time in the user's local timezone
    now_local = datetime.now(local_tz)
    local_midnight = now_local.replace(hour=0, minute=0, second=0, microsecond=0)
    
    if period == "today":
        start = local_midnight
        end = local_midnight + timedelta(days=1)
    elif period == "week":
        start = local_midnight - timedelta(days=7)
        end = local_midnight + timedelta(days=1)
    elif period == "month":
        start = local_midnight - timedelta(days=30)
        end = local_midnight + timedelta(days=1)
    elif period == "all":
        start = datetime(2020, 1, 1, tzinfo=local_tz)
        end = local_midnight + timedelta(days=1)
    else:
        start = local_midnight
        end = local_midnight + timedelta(days=1)
    
    # Convert to UTC for MongoDB queries
    start_utc = start.astimezone(timezone.utc)
    end_utc = end.astimezone(timezone.utc)
    
    return start_utc, end_utc

PRIORITY_ORDER = {"high": 1, "medium": 2, "low": 3}

# ── Unified "Texts Sent" types ──
# Sending a card or link via SMS IS sending a text. Count everything that
# opens the native SMS app as a text for dashboard purposes.
SMS_EVENT_TYPES = [
    "sms_sent", "sms_personal", "personal_sms", "sms_failed",
    # Cards sent via SMS
    "congrats_card_sent", "birthday_card_sent", "holiday_card_sent",
    "thank_you_card_sent", "thankyou_card_sent", "anniversary_card_sent",
    "welcome_card_sent",
    # Digital card / vCard shares
    "digital_card_sent", "digital_card_shared", "card_shared", "vcard_sent",
    # Review & link shares via SMS
    "review_request_sent", "review_shared", "review_invite_sent",
    # Showcase / link page shares
    "link_page_shared", "showcase_shared", "showroom_shared",
]

def count_texts(activity: dict) -> int:
    """Sum all event types that represent a text/SMS being sent."""
    return sum(activity.get(t, 0) for t in SMS_EVENT_TYPES)


def _serialize(task: dict) -> dict:
    """Serialize a task for JSON response."""
    task["_id"] = str(task["_id"])
    for key in ("due_date", "created_at", "completed_at", "snoozed_until"):
        val = task.get(key)
        if isinstance(val, datetime):
            task[key] = val.isoformat()
    for key in ("contact_id", "campaign_id"):
        if isinstance(task.get(key), ObjectId):
            task[key] = str(task[key])
    # Legacy compat: map completed bool → status
    if task.get("completed") and task.get("status") != "completed":
        task["status"] = "completed"
    if not task.get("status"):
        task["status"] = "pending"
    return task


@router.get("/{user_id}")
async def get_tasks(user_id: str, filter: str = "today", limit: int = 50, skip: int = 0):
    """
    Get tasks. Filters: today (due today + overdue), overdue, upcoming, completed, all
    """
    db = get_db()

    # Catch-up: create tasks for overdue campaign steps when viewing today's tasks
    if filter in ("today", "overdue"):
        await _catchup_overdue_campaign_tasks(user_id)

    today_start, today_end = await get_user_day_bounds(user_id, "today")
    now = datetime.now(timezone.utc)

    base = {"user_id": user_id}

    if filter == "today":
        base["status"] = {"$in": ["pending", "snoozed", None]}
        base["$or"] = [
            {"due_date": {"$lte": today_end}},
            {"due_date": {"$exists": False}},
            {"due_date": None},
        ]
    elif filter == "overdue":
        base["status"] = {"$in": ["pending", None]}
        base["due_date"] = {"$lt": today_start}
    elif filter == "upcoming":
        base["status"] = {"$in": ["pending", "snoozed", None]}
        base["due_date"] = {"$gt": today_end}
    elif filter == "completed":
        base["$or"] = [{"status": "completed"}, {"completed": True}]
    # else: "all" — no status filter

    tasks = await db.tasks.find(base).sort([
        ("priority_order", 1),
        ("due_date", 1),
        ("created_at", -1),
    ]).skip(skip).limit(limit).to_list(limit)

    # Post-filter snoozed tasks not yet due
    result = []
    for t in tasks:
        snoozed_until = t.get("snoozed_until")
        if t.get("status") == "snoozed" and snoozed_until and isinstance(snoozed_until, datetime):
            if snoozed_until.replace(tzinfo=timezone.utc if snoozed_until.tzinfo is None else snoozed_until.tzinfo) > now:
                continue
        result.append(_serialize(t))

    return result


@router.get("/{user_id}/summary")
async def get_task_summary(user_id: str):
    """Daily summary for scoreboard + progress bar."""
    db = get_db()

    # Catch-up: create tasks for overdue campaign steps that the scheduler missed
    await _catchup_overdue_campaign_tasks(user_id)

    today_start, today_end = await get_user_day_bounds(user_id, "today")
    now = datetime.now(timezone.utc)

    total_today = await db.tasks.count_documents({
        "user_id": user_id,
        "status": {"$nin": ["dismissed", "completed"]},
        "$or": [
            {"due_date": {"$gte": today_start, "$lte": today_end}},
            {"due_date": {"$exists": False}},
            {"due_date": None},
        ],
    })

    completed_today = await db.tasks.count_documents({
        "user_id": user_id,
        "$or": [
            {"status": "completed", "completed_at": {"$gte": today_start, "$lt": today_end}},
            {"completed": True, "created_at": {"$gte": today_start, "$lt": today_end}},
        ],
    })

    pending = await db.tasks.count_documents({
        "user_id": user_id,
        "status": {"$in": ["pending", "snoozed", None]},
        "$or": [
            {"due_date": {"$lte": today_end}},
            {"due_date": {"$exists": False}},
            {"due_date": None},
        ],
    })

    overdue = await db.tasks.count_documents({
        "user_id": user_id,
        "status": {"$in": ["pending", None]},
        "completed": {"$ne": True},
        "due_date": {"$lt": today_start},
    })

    # Today's activity from contact_events
    activity = {}
    try:
        pipeline = [
            {"$match": {"user_id": user_id, "timestamp": {"$gte": today_start, "$lt": today_end}}},
            {"$group": {"_id": "$event_type", "count": {"$sum": 1}}},
        ]
        for r in await db.contact_events.aggregate(pipeline).to_list(50):
            activity[r["_id"]] = r["count"]
    except Exception:
        pass

    # Today's engagement signals (card views, link clicks, showcase views, etc.)
    engagement = {}
    try:
        eng_pipeline = [
            {"$match": {"user_id": user_id, "created_at": {"$gte": today_start, "$lt": today_end}}},
            {"$group": {"_id": "$signal_type", "count": {"$sum": 1}}},
        ]
        for r in await db.engagement_signals.aggregate(eng_pipeline).to_list(50):
            engagement[r["_id"]] = r["count"]
    except Exception:
        pass

    # New leads today
    new_leads = 0
    try:
        new_leads = await db.contacts.count_documents({
            "$or": [{"user_id": user_id}, {"created_by": user_id}],
            "created_at": {"$gte": today_start, "$lt": today_end},
        })
    except Exception:
        pass

    # Aggregate engagement clicks/opens
    total_clicks = (
        engagement.get("card_viewed", 0) +
        engagement.get("digital_card_viewed", 0) +
        engagement.get("link_clicked", 0) +
        engagement.get("review_link_clicked", 0) +
        engagement.get("showcase_viewed", 0) +
        engagement.get("link_page_viewed", 0) +
        activity.get("link_clicked", 0) +
        activity.get("card_viewed", 0) +
        activity.get("showcase_viewed", 0)
    )
    total_opens = (
        engagement.get("contact_saved", 0) +
        activity.get("email_opened", 0)
    )
    total_replies = (
        activity.get("reply_received", 0) +
        activity.get("sms_received", 0)
    )

    # Cards sent (only outbound SEND actions — exclude customer views/downloads/shares)
    cards_sent = sum(v for k, v in activity.items() if k and ("_card_sent" in k or "card_shared" in k or "digital_card_shared" in k))

    texts_sent = count_texts(activity)

    # Activities are completed touchpoints (user already performed the action)
    # Use texts_sent which already includes card sends — don't double-count
    activity_touchpoints = (
        texts_sent +
        activity.get("email_sent", 0) + activity.get("email_failed", 0) +
        activity.get("call_placed", 0)
    )

    combined_total = total_today + activity_touchpoints
    combined_completed = completed_today + activity_touchpoints

    return {
        "total_today": combined_total,
        "completed_today": combined_completed,
        "pending_today": pending,
        "overdue": overdue,
        "progress_pct": round((combined_completed / max(combined_total, 1)) * 100) if combined_total > 0 else 0,
        "activity": {
            "calls": activity.get("call_placed", 0) + activity.get("call_received", 0),
            "texts": texts_sent,
            "emails": activity.get("email_sent", 0) + activity.get("email_failed", 0),
            "cards": cards_sent,
            "reviews": activity.get("review_invite_sent", 0) + activity.get("review_shared", 0) + activity.get("review_request_sent", 0),
            "clicks": total_clicks,
            "opens": total_opens,
            "replies": total_replies,
            "new_leads": new_leads,
        },
    }


@router.post("/{user_id}")
async def create_task(user_id: str, task_data: dict):
    """Create a manual task. Required: title. Optional: contact_id, description, due_date, etc."""
    db = get_db()
    title = (task_data.get("title") or "").strip()
    if not title:
        raise HTTPException(status_code=400, detail="Title is required")

    contact_id = task_data.get("contact_id", "")
    contact_name = task_data.get("contact_name", "")
    contact_phone = task_data.get("contact_phone", "")

    if contact_id and not contact_name:
        try:
            c = await db.contacts.find_one({"_id": ObjectId(contact_id)})
            if c:
                contact_name = f"{c.get('first_name','')} {c.get('last_name','')}".strip()
                contact_phone = c.get("phone", "")
        except Exception:
            pass

    due_date = None
    if task_data.get("due_date"):
        try:
            due_date = datetime.fromisoformat(str(task_data["due_date"]).replace("Z", "+00:00"))
        except Exception:
            due_date = datetime.now(timezone.utc)
    else:
        due_date = datetime.now(timezone.utc)

    priority = task_data.get("priority", "medium")

    task = {
        "user_id": user_id,
        "contact_id": contact_id,
        "contact_name": contact_name,
        "contact_phone": contact_phone,
        "type": task_data.get("type", "manual"),
        "source": "manual",
        "title": title,
        "description": task_data.get("description", ""),
        "suggested_message": task_data.get("suggested_message", ""),
        "action_type": task_data.get("action_type", "manual"),
        "priority": priority,
        "priority_order": PRIORITY_ORDER.get(priority, 2),
        "status": "pending",
        "completed": False,
        "due_date": due_date,
        "completed_at": None,
        "snoozed_until": None,
        "campaign_id": None,
        "campaign_name": None,
        "pending_send_id": None,
        "channel": task_data.get("channel", ""),
        "created_at": datetime.now(timezone.utc),
    }

    result = await db.tasks.insert_one(task)
    task["_id"] = str(result.inserted_id)
    logger.info(f"Manual task created: '{title}' for user {user_id}")

    # Log as contact_event so it appears in the contact's activity timeline
    if contact_id:
        await db.contact_events.insert_one({
            "contact_id": contact_id,
            "user_id": user_id,
            "event_type": "task_created",
            "channel": "system",
            "content_preview": title,
            "metadata": {
                "task_id": task["_id"],
                "description": task_data.get("description", ""),
                "priority": priority,
                "due_date": due_date.isoformat() if due_date else None,
            },
            "timestamp": datetime.now(timezone.utc),
        })

    return _serialize(task)


@router.patch("/{user_id}/{task_id}")
async def update_task(user_id: str, task_id: str, update_data: dict):
    """Update a task: complete, snooze, dismiss, or edit fields."""
    db = get_db()
    task = await db.tasks.find_one({"_id": ObjectId(task_id), "user_id": user_id})
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    action = update_data.get("action", "edit")
    updates = {}

    if action == "complete":
        updates["status"] = "completed"
        updates["completed"] = True
        updates["completed_at"] = datetime.now(timezone.utc)
        # Log completion event
        cid = task.get("contact_id", "")
        if cid:
            try:
                user = await get_user_by_id(user_id)
                await db.contact_events.insert_one({
                    "event_type": "task_completed",
                    "title": f"Task Completed: {task.get('title', '')}",
                    "user_id": user_id,
                    "contact_id": cid,
                    "org_id": (user or {}).get("organization_id", ""),
                    "description": task.get("description", ""),
                    "timestamp": datetime.now(timezone.utc),
                    "source": task.get("source", "manual"),
                })
            except Exception as e:
                logger.error(f"Failed to log task completion: {e}")
        # When a campaign task is completed, update the enrollment's messages_sent status
        if task.get("type") == "campaign_send" and task.get("campaign_id") and cid:
            try:
                pending_send_id = task.get("pending_send_id", "")
                step_num = None
                if pending_send_id:
                    ps = await db.campaign_pending_sends.find_one({"_id": ObjectId(pending_send_id)})
                    step_num = (ps or {}).get("step")
                if step_num:
                    await db.campaign_enrollments.update_one(
                        {
                            "campaign_id": task["campaign_id"],
                            "contact_id": cid,
                            "messages_sent.step": step_num,
                        },
                        {
                            "$set": {
                                "messages_sent.$.status": "sent",
                                "messages_sent.$.sent_at": datetime.now(timezone.utc),
                                "last_sent_at": datetime.now(timezone.utc),
                            }
                        }
                    )
            except Exception as e:
                logger.warning(f"Failed to update campaign enrollment on task complete: {e}")

    elif action == "snooze":
        hours = update_data.get("snooze_hours", 24)
        snooze_until = datetime.now(timezone.utc) + timedelta(hours=hours)
        updates["status"] = "snoozed"
        updates["snoozed_until"] = snooze_until
        updates["due_date"] = snooze_until

    elif action == "dismiss":
        updates["status"] = "dismissed"

    elif action == "edit":
        for f in ("title", "description", "priority", "action_type", "suggested_message"):
            if f in update_data:
                updates[f] = update_data[f]
                if f == "priority":
                    updates["priority_order"] = PRIORITY_ORDER.get(update_data[f], 2)
        if "due_date" in update_data:
            try:
                updates["due_date"] = datetime.fromisoformat(str(update_data["due_date"]).replace("Z", "+00:00"))
            except Exception:
                pass

    if updates:
        await db.tasks.update_one({"_id": ObjectId(task_id)}, {"$set": updates})

    updated = await db.tasks.find_one({"_id": ObjectId(task_id)})
    return _serialize(updated)


# Keep legacy PUT for backward compat
@router.put("/{user_id}/{task_id}")
async def update_task_legacy(user_id: str, task_id: str, task_data: dict):
    """Legacy update endpoint."""
    db = get_db()
    allowed = ["completed", "title", "description", "due_date", "type", "priority", "status"]
    update_dict = {k: v for k, v in task_data.items() if k in allowed}
    if "completed" in update_dict and update_dict["completed"]:
        update_dict["status"] = "completed"
        update_dict["completed_at"] = datetime.now(timezone.utc)
    update_dict["updated_at"] = datetime.now(timezone.utc)

    result = await db.tasks.update_one(
        {"_id": ObjectId(task_id), "user_id": user_id},
        {"$set": update_dict}
    )
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Task not found")
    return {"message": "Task updated successfully"}


@router.delete("/{user_id}/{task_id}")
async def delete_task(user_id: str, task_id: str):
    """Delete a task."""
    result = await get_db().tasks.delete_one({"_id": ObjectId(task_id), "user_id": user_id})
    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Task not found")
    return {"success": True}


@router.get("/{user_id}/performance")
async def get_performance(user_id: str, period: str = "week"):
    """Performance stats for My Performance page. period: today, week, month"""
    db = get_db()
    now = datetime.now(timezone.utc)
    start, end = await get_user_day_bounds(user_id, period)

    match = {"user_id": user_id, "timestamp": {"$gte": start, "$lt": end}}

    # Define actual customer-facing touchpoint types (not internal events like tag_added, contact_added)
    TOUCHPOINT_EVENT_TYPES = SMS_EVENT_TYPES + [
        "email_sent", "email_failed",
        "call_placed", "call_received",
    ]

    # Aggregate events by type
    pipeline = [
        {"$match": match},
        {"$group": {"_id": "$event_type", "count": {"$sum": 1}}},
    ]
    activity = {}
    for r in await db.contact_events.aggregate(pipeline).to_list(100):
        activity[r["_id"]] = r["count"]

    # Also aggregate engagement_signals for the same period
    eng_match = {"user_id": user_id, "created_at": {"$gte": start, "$lt": end}}
    eng_pipeline = [
        {"$match": eng_match},
        {"$group": {"_id": "$signal_type", "count": {"$sum": 1}}},
    ]
    eng_signals = {}
    try:
        for r in await db.engagement_signals.aggregate(eng_pipeline).to_list(100):
            eng_signals[r["_id"]] = r["count"]
    except Exception:
        pass

    # Previous period for trend — only count actual touchpoints
    period_length = end - start
    prev_start = start - period_length
    touchpoint_match = {"user_id": user_id, "event_type": {"$in": TOUCHPOINT_EVENT_TYPES}, "timestamp": {"$gte": start, "$lt": end}}
    prev_touchpoint_match = {"user_id": user_id, "event_type": {"$in": TOUCHPOINT_EVENT_TYPES}, "timestamp": {"$gte": prev_start, "$lt": start}}
    prev_total = await db.contact_events.count_documents(prev_touchpoint_match)
    curr_total = await db.contact_events.count_documents(touchpoint_match)
    # Include engagement signals in total
    eng_total = sum(eng_signals.values())
    curr_total += eng_total
    try:
        prev_eng = await db.engagement_signals.count_documents({"user_id": user_id, "created_at": {"$gte": prev_start, "$lt": start}})
        prev_total += prev_eng
    except Exception:
        pass
    trend_pct = round(((curr_total - prev_total) / max(prev_total, 1)) * 100) if prev_total else 0

    # New contacts added
    new_leads = await db.contacts.count_documents({
        "$or": [{"user_id": user_id}, {"created_by": user_id}],
        "created_at": {"$gte": start, "$lt": end},
    })

    # Daily scorecard: today vs yesterday (always calculated using user's local timezone)
    # Only count actual customer-facing touchpoints, not internal events (tag_added, contact_added, etc.)
    today_start_tz, today_end_tz = await get_user_day_bounds(user_id, "today")
    yesterday_start_tz = today_start_tz - timedelta(days=1)
    touchpoint_filter = {"user_id": user_id, "event_type": {"$in": TOUCHPOINT_EVENT_TYPES}}
    today_events = await db.contact_events.count_documents({**touchpoint_filter, "timestamp": {"$gte": today_start_tz, "$lt": today_end_tz}})
    yesterday_events = await db.contact_events.count_documents({**touchpoint_filter, "timestamp": {"$gte": yesterday_start_tz, "$lt": today_start_tz}})
    try:
        today_eng = await db.engagement_signals.count_documents({"user_id": user_id, "created_at": {"$gte": today_start_tz, "$lt": today_end_tz}})
        yesterday_eng = await db.engagement_signals.count_documents({"user_id": user_id, "created_at": {"$gte": yesterday_start_tz, "$lt": today_start_tz}})
        today_events += today_eng
        yesterday_events += yesterday_eng
    except Exception:
        pass

    # Streak: consecutive days with 5+ touchpoints (looking back up to 90 days)
    STREAK_THRESHOLD = 5
    streak = 0
    if today_events >= STREAK_THRESHOLD:
        streak = 1
    for days_ago in range(1, 91):
        day_start = today_start_tz - timedelta(days=days_ago)
        day_end = day_start + timedelta(days=1)
        day_count = await db.contact_events.count_documents({**touchpoint_filter, "timestamp": {"$gte": day_start, "$lt": day_end}})
        try:
            day_count += await db.engagement_signals.count_documents({"user_id": user_id, "created_at": {"$gte": day_start, "$lt": day_end}})
        except Exception:
            pass
        if day_count >= STREAK_THRESHOLD:
            streak += 1
        else:
            break

    # Personal bests: best day and best week in last 90 days
    best_day = 0
    best_day_date = None
    ninety_days_ago = today_start_tz - timedelta(days=90)
    pipeline = [
        {"$match": {"user_id": user_id, "timestamp": {"$gte": ninety_days_ago}}},
        {"$group": {
            "_id": {"$dateToString": {"format": "%Y-%m-%d", "date": "$timestamp"}},
            "count": {"$sum": 1},
        }},
        {"$sort": {"count": -1}},
        {"$limit": 1},
    ]
    best_day_result = await db.contact_events.aggregate(pipeline).to_list(1)
    if best_day_result:
        best_day = best_day_result[0]["count"]
        best_day_date = best_day_result[0]["_id"]

    best_week = 0
    week_pipeline = [
        {"$match": {"user_id": user_id, "timestamp": {"$gte": ninety_days_ago}}},
        {"$group": {
            "_id": {"$isoWeek": "$timestamp"},
            "count": {"$sum": 1},
        }},
        {"$sort": {"count": -1}},
        {"$limit": 1},
    ]
    best_week_result = await db.contact_events.aggregate(week_pipeline).to_list(1)
    if best_week_result:
        best_week = best_week_result[0]["count"]

    # Check for milestone notifications (non-blocking)
    try:
        from routers.push_notifications import check_and_notify_milestones
        user_total = await db.contact_events.count_documents({"user_id": user_id})
        levels = [(0, "Rookie"), (100, "Hustler"), (500, "Closer"), (1500, "All-Star"), (5000, "Legend")]
        level_title = "Rookie"
        for threshold, name in levels:
            if user_total >= threshold:
                level_title = name
        import asyncio as _asyncio
        _asyncio.create_task(check_and_notify_milestones(user_id, streak, level_title, today_events, best_day))
    except Exception as e:
        logger.warning(f"Milestone check failed: {e}")

    total_touchpoints = (
        count_texts(activity) +
        activity.get("email_sent", 0) + activity.get("email_failed", 0) +
        activity.get("call_placed", 0) + activity.get("call_received", 0) +
        eng_total
    )

    # ── Customer card engagement: count ALL *_card_viewed and *_card_download(ed) events dynamically ──
    # This auto-includes any card type (congrats, welcome, birthday, holiday, thankyou, anniversary, and ANY future type)
    # Excludes digital_card_* and store_card_* which are separate metrics
    card_engagement_total = eng_signals.get("card_viewed", 0) + eng_signals.get("card_downloaded", 0)
    for evt_key, evt_count in activity.items():
        if ("_card_viewed" in evt_key or "_card_download" in evt_key) and not evt_key.startswith("digital_card") and not evt_key.startswith("store_card"):
            card_engagement_total += evt_count

    # ── Card shares: count ALL *_card_sent events dynamically ──
    card_shares_total = 0
    for evt_key, evt_count in activity.items():
        if "_card_sent" in evt_key:
            card_shares_total += evt_count

    return {
        "total_touchpoints": total_touchpoints,
        "trend_pct": trend_pct,
        "scorecard": {
            "today": today_events,
            "yesterday": yesterday_events,
            "diff": today_events - yesterday_events,
            "streak": streak,
            "streak_threshold": STREAK_THRESHOLD,
        },
        "personal_bests": {
            "best_day": best_day,
            "best_day_date": best_day_date,
            "best_week": best_week,
        },
        "communication": {
            "texts": count_texts(activity),
            "emails": activity.get("email_sent", 0) + activity.get("email_failed", 0),
            "calls": activity.get("call_placed", 0) + activity.get("call_received", 0),
        },
        "sharing": {
            "my_card": activity.get("digital_card_shared", 0) + activity.get("card_shared", 0) + activity.get("digital_card_sent", 0),
            "reviews": activity.get("review_invite_sent", 0) + activity.get("review_shared", 0) + activity.get("review_request_sent", 0),
            "card_shares": card_shares_total,
            "showcase": activity.get("showroom_shared", 0),
        },
        "engagement": {
            "link_clicks": activity.get("link_clicked", 0) + activity.get("card_viewed", 0) + eng_signals.get("link_clicked", 0) + eng_signals.get("card_viewed", 0) + eng_signals.get("digital_card_viewed", 0) + eng_signals.get("showcase_viewed", 0) + eng_signals.get("link_page_viewed", 0) + eng_signals.get("review_link_clicked", 0),
            "email_opens": activity.get("email_opened", 0),
            "replies": activity.get("reply_received", 0) + activity.get("sms_received", 0),
            "new_leads": new_leads,
        },
        "click_through": {
            "my_card_views": activity.get("digital_card_viewed", 0) + eng_signals.get("digital_card_viewed", 0),
            "customer_card_views": card_engagement_total,
            "review_link_clicks": activity.get("review_link_clicked", 0) + activity.get("online_review_clicked", 0) + activity.get("card_review_clicked", 0) + activity.get("card_online_review_clicked", 0) + eng_signals.get("review_link_clicked", 0),
            "showcase_views": activity.get("showcase_viewed", 0) + activity.get("showroom_viewed", 0) + eng_signals.get("showcase_viewed", 0),
            "link_page_visits": activity.get("link_page_viewed", 0) + eng_signals.get("link_page_viewed", 0),
        },
    }



EVENT_CATEGORY_MAP = {
    "texts": SMS_EVENT_TYPES,
    "emails": ["email_sent", "email_failed"],
    "calls": ["call_placed", "call_received"],
    "my_card": ["digital_card_shared", "card_shared", "digital_card_sent"],
    "reviews": ["review_invite_sent", "review_shared", "review_request_sent"],
    "card_shares": ["congrats_card_sent", "birthday_card_sent", "holiday_card_sent", "thank_you_card_sent", "anniversary_card_sent", "welcome_card_sent", "thankyou_card_sent"],
    "showcase": ["showroom_shared"],
    "link_clicks": ["link_clicked", "card_viewed"],
    "email_opens": ["email_opened"],
    "replies": ["reply_received", "sms_received"],
    "my_card_views": ["digital_card_viewed"],
    "customer_card_views": "__REGEX__:^(?!digital_|store_).*_card_(viewed|download)",
    "review_link_clicks": ["review_link_clicked", "online_review_clicked", "card_review_clicked", "card_online_review_clicked"],
    "showcase_views": ["showcase_viewed", "showroom_viewed"],
    "link_page_visits": ["link_page_viewed"],
}

# Engagement signal types that map to detail categories (from engagement_signals collection)
ENGAGEMENT_CATEGORY_MAP = {
    "link_clicks": ["link_clicked", "card_viewed", "digital_card_viewed", "showcase_viewed", "link_page_viewed", "review_link_clicked"],
    "my_card_views": ["digital_card_viewed"],
    "customer_card_views": "__REGEX__:^(?!digital_|store_).*_card_(viewed|download)",
    "review_link_clicks": ["review_link_clicked", "online_review_clicked", "card_review_clicked", "card_online_review_clicked"],
    "showcase_views": ["showcase_viewed"],
    "link_page_visits": ["link_page_viewed"],
}

@router.get("/{user_id}/performance/detail")
async def get_performance_detail(user_id: str, category: str, period: str = "week"):
    """Get recent activity for a specific touchpoint category."""
    db = get_db()
    start, end = await get_user_day_bounds(user_id, period)

    event_types = EVENT_CATEGORY_MAP.get(category, [])

    # Special case: new_leads — pull from contacts collection
    if category == "new_leads":
        contacts = await db.contacts.find(
            {
                "$or": [{"user_id": user_id}, {"created_by": user_id}],
                "created_at": {"$gte": start, "$lt": end},
            },
            {"_id": 1, "first_name": 1, "last_name": 1, "phone": 1, "created_at": 1, "source": 1},
        ).sort("created_at", -1).limit(50).to_list(50)
        events = []
        for c in contacts:
            events.append({
                "event_type": "new_lead",
                "contact_name": f"{c.get('first_name', '')} {c.get('last_name', '')}".strip() or c.get("phone", "Unknown"),
                "contact_id": str(c["_id"]),
                "content": f"Added via {c.get('source', 'manual')}",
                "timestamp": c["created_at"].isoformat() if c.get("created_at") else None,
            })
        return {"events": events, "count": len(events)}

    # Build event filter — supports regex patterns for generic card-type matching
    if isinstance(event_types, str) and event_types.startswith("__REGEX__:"):
        regex_pattern = event_types.split(":", 1)[1]
        event_filter = {"$regex": regex_pattern}
    elif event_types:
        event_filter = {"$in": event_types}
    else:
        return {"events": []}

    events = await db.contact_events.find(
        {"user_id": user_id, "event_type": event_filter, "timestamp": {"$gte": start, "$lt": end}},
        {"_id": 0, "event_type": 1, "channel": 1, "content": 1, "contact_id": 1, "contact_name": 1, "timestamp": 1}
    ).sort("timestamp", -1).limit(50).to_list(50)

    # Also pull from engagement_signals for click-through categories
    eng_types = ENGAGEMENT_CATEGORY_MAP.get(category, [])
    if isinstance(eng_types, str) and eng_types.startswith("__REGEX__:"):
        eng_regex = eng_types.split(":", 1)[1]
        eng_filter = {"$regex": eng_regex}
    elif eng_types:
        eng_filter = {"$in": eng_types}
    else:
        eng_filter = None
    if eng_filter:
        try:
            eng_events = await db.engagement_signals.find(
                {"user_id": user_id, "signal_type": eng_filter, "created_at": {"$gte": start, "$lt": end}},
                {"_id": 0, "signal_type": 1, "contact_id": 1, "contact_name": 1, "created_at": 1, "metadata": 1},
            ).sort("created_at", -1).limit(50).to_list(50)
            for e in eng_events:
                events.append({
                    "event_type": e.get("signal_type", ""),
                    "contact_name": e.get("contact_name", "Anonymous"),
                    "contact_id": e.get("contact_id", ""),
                    "content": e.get("metadata", {}).get("source", "") if isinstance(e.get("metadata"), dict) else "",
                    "timestamp": e["created_at"].isoformat() if e.get("created_at") else None,
                })
        except Exception:
            pass

    # Enrich with contact names if missing
    contact_ids = [e.get("contact_id") for e in events if e.get("contact_id") and not e.get("contact_name")]
    if contact_ids:
        contacts = {}
        for c in await db.contacts.find({"_id": {"$in": [ObjectId(cid) for cid in contact_ids if len(str(cid)) == 24]}}, {"first_name": 1, "last_name": 1}).to_list(100):
            contacts[str(c["_id"])] = f"{c.get('first_name', '')} {c.get('last_name', '')}".strip()
        for e in events:
            if e.get("contact_id") and not e.get("contact_name"):
                e["contact_name"] = contacts.get(e["contact_id"], "Unknown")

    for e in events:
        if e.get("timestamp") and hasattr(e["timestamp"], 'isoformat'):
            e["timestamp"] = e["timestamp"].isoformat()

    return {"events": events, "count": len(events)}


@router.post("/{user_id}/generate-system-tasks")
async def generate_system_tasks(user_id: str):
    """
    Generate system tasks: dormant contacts (90+ days), upcoming birthdays, purchase anniversaries.
    Uses idempotency keys to prevent duplicates.
    """
    db = get_db()
    now = datetime.now(timezone.utc)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    created = 0

    user = await get_user_by_id(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    # === DORMANT CONTACTS (no event in 90+ days) ===
    # CRITICAL: Only use the user's OWN contacts, not org-wide contacts
    # Each user's system tasks must be based solely on their own contact list
    cutoff = now - timedelta(days=90)
    contacts = await db.contacts.find({
        "user_id": user_id,
        "phone": {"$exists": True, "$ne": ""},
        "status": {"$nin": ["hidden", "merged", "deleted"]},
    }).to_list(500)

    for contact in contacts:
        cid = str(contact["_id"])
        name = f"{contact.get('first_name','')} {contact.get('last_name','')}".strip()
        if not name:
            continue

        last = await db.contact_events.find_one(
            {"contact_id": cid, "user_id": user_id},
            sort=[("timestamp", -1)]
        )
        last_ts = (last or {}).get("timestamp") or contact.get("created_at")
        if not last_ts or not isinstance(last_ts, datetime):
            continue

        if last_ts.tzinfo is None:
            last_ts = last_ts.replace(tzinfo=timezone.utc)
        if last_ts < cutoff:
            idem = f"dormant_{user_id}_{cid}_{today_start.strftime('%Y-%m-%d')}"
            if await db.tasks.find_one({"idempotency_key": idem}):
                continue
            days = (now - last_ts).days
            await db.tasks.insert_one({
                "user_id": user_id, "contact_id": cid,
                "contact_name": name, "contact_phone": contact.get("phone", ""),
                "type": "follow_up", "source": "system",
                "title": f"Reconnect with {name}",
                "description": f"It's been {days} days since your last interaction.",
                "suggested_message": f"Hey {contact.get('first_name','there')}! It's been a while — just wanted to check in and see how things are going!",
                "action_type": "text", "priority": "medium", "priority_order": 2,
                "status": "pending", "completed": False,
                "due_date": now, "channel": "sms",
                "created_at": now, "idempotency_key": idem,
            })
            created += 1

    # === UPCOMING BIRTHDAYS (next 3 days) ===
    bday_contacts = await db.contacts.find({
        "user_id": user_id, "birthday": {"$exists": True, "$ne": None},
        "status": {"$nin": ["hidden", "merged", "deleted"]},
    }).to_list(500)

    for offset in range(4):
        check = now + timedelta(days=offset)
        cm, cd = check.month, check.day
        for contact in bday_contacts:
            bday = contact.get("birthday")
            if bday and isinstance(bday, datetime) and bday.month == cm and bday.day == cd:
                cid = str(contact["_id"])
                name = f"{contact.get('first_name','')} {contact.get('last_name','')}".strip()
                idem = f"birthday_{user_id}_{cid}_{check.strftime('%Y-%m-%d')}"
                if await db.tasks.find_one({"idempotency_key": idem}):
                    continue
                label = "today" if offset == 0 else f"in {offset} day{'s' if offset > 1 else ''}"
                await db.tasks.insert_one({
                    "user_id": user_id, "contact_id": cid,
                    "contact_name": name, "contact_phone": contact.get("phone", ""),
                    "type": "birthday", "source": "system",
                    "title": f"Birthday {label}: {name}",
                    "description": f"Send {contact.get('first_name','') or name} a personal birthday message!",
                    "suggested_message": f"Happy Birthday, {contact.get('first_name','')}! Hope you have an amazing day!",
                    "action_type": "text",
                    "priority": "high" if offset == 0 else "medium",
                    "priority_order": 1 if offset == 0 else 2,
                    "status": "pending", "completed": False,
                    "due_date": check.replace(hour=9, minute=0, second=0),
                    "channel": "sms", "created_at": now, "idempotency_key": idem,
                })
                created += 1

    # === PURCHASE ANNIVERSARIES (next 3 days) ===
    sold_contacts = await db.contacts.find({
        "user_id": user_id,
        "status": {"$nin": ["hidden", "merged", "deleted"]},
        "$or": [
            {"date_sold": {"$exists": True, "$ne": None}},
            {"purchase_date": {"$exists": True, "$ne": None}},
        ],
    }).to_list(500)

    for offset in range(4):
        check = now + timedelta(days=offset)
        cm, cd = check.month, check.day
        for contact in sold_contacts:
            sd = contact.get("date_sold") or contact.get("purchase_date")
            if sd and isinstance(sd, datetime) and sd.month == cm and sd.day == cd and sd.year != check.year:
                cid = str(contact["_id"])
                name = f"{contact.get('first_name','')} {contact.get('last_name','')}".strip()
                years = check.year - sd.year
                idem = f"anniversary_{user_id}_{cid}_{check.strftime('%Y-%m-%d')}"
                if await db.tasks.find_one({"idempotency_key": idem}):
                    continue
                label = "today" if offset == 0 else f"in {offset} day{'s' if offset > 1 else ''}"
                await db.tasks.insert_one({
                    "user_id": user_id, "contact_id": cid,
                    "contact_name": name, "contact_phone": contact.get("phone", ""),
                    "type": "anniversary", "source": "system",
                    "title": f"{years}-Year Anniversary {label}: {name}",
                    "description": f"It's been {years} year{'s' if years>1 else ''} since {name}'s purchase.",
                    "suggested_message": f"Hey {contact.get('first_name','')}! Can you believe it's been {years} year{'s' if years>1 else ''} already? Hope everything's still going great!",
                    "action_type": "text",
                    "priority": "high" if offset == 0 else "medium",
                    "priority_order": 1 if offset == 0 else 2,
                    "status": "pending", "completed": False,
                    "due_date": check.replace(hour=9, minute=0, second=0),
                    "channel": "sms", "created_at": now, "idempotency_key": idem,
                })
                created += 1

    logger.info(f"System tasks generated for {user_id}: {created} new")
    return {"created": created, "user_id": user_id}
