"""
Internal Training Curriculum Seed Script
Run once: python3 scripts/seed_internal_training.py

Creates 8 training tracks with full lesson content covering:
  1. Platform Setup & Configuration
  2. Customer Support Playbook
  3. Account Onboarding
  4. Account Management
  5. Billing & Subscriptions
  6. Technical Reference
  7. Sales Process
  8. Marketing Playbook
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()


INTERNAL_TRACKS = [

    # ─── 1. PLATFORM SETUP & CONFIGURATION ───────────────────────────────────
    {
        "slug": "platform-setup",
        "title": "Platform Setup & Configuration",
        "description": "Complete guide to setting up and configuring every part of the I'm On Social platform — from initial org creation to integrations.",
        "icon": "construct",
        "color": "#007AFF",
        "roles": ["super_admin", "org_admin", "admin", "store_manager"],
        "order": 10,
        "lessons": [
            {
                "slug": "setup-org-store",
                "title": "Creating an Organization & Store",
                "description": "Set up the account hierarchy — organization, store, and initial super admin.",
                "icon": "business",
                "duration": "5 min",
                "order": 1,
                "video_url": "",
                "content": "## Creating an Organization & Store\n\nEvery account in I'm On Social is scoped to an Organization → Store hierarchy. This determines what data each user can see and who gets routed which leads.\n\n### When to Use\nUse this when onboarding a brand-new client or creating a demo account.",
                "steps": [
                    "Log in as super_admin",
                    "Navigate to Hub → Account Management → Organizations",
                    "Tap '+' to create a new organization — enter company name, address, timezone",
                    "Open the new organization and tap 'Add Store' — fill in store name, phone, location",
                    "Return to Hub → Account Management → All Users → find the owner and set their Organization and Store fields",
                    "Confirm the user now sees the correct store in their profile under Hub → My Account",
                ],
            },
            {
                "slug": "setup-invite-team",
                "title": "Inviting & Managing Team Members",
                "description": "Add users to an account and assign the correct roles and permissions.",
                "icon": "person-add",
                "duration": "5 min",
                "order": 2,
                "video_url": "",
                "content": "## Inviting & Managing Team Members\n\nEvery person who needs to use the platform needs an account. Roles control what they can see and do.\n\n### Role Definitions\n- **super_admin** — Full platform access, all accounts\n- **org_admin / admin** — Manages one organization\n- **store_manager** — Manages one store's users and settings\n- **user** — Standard sales rep",
                "steps": [
                    "Go to Hub → Set Up → Team Members",
                    "Tap 'Invite Team Member' and enter their name, email, and role",
                    "They receive an invite email with a registration link",
                    "After they register, go back to Team Members and assign their Store and Organization",
                    "For permission customization: open the user → tap Permissions → use a permission template or customize individually",
                    "Verify by impersonating the user (super_admin only): Hub → All Users → tap user → 'Impersonate'",
                ],
            },
            {
                "slug": "setup-twilio-numbers",
                "title": "Assigning Twilio Phone Numbers",
                "description": "Purchase, assign, and verify Twilio phone numbers for each rep.",
                "icon": "call",
                "duration": "5 min",
                "order": 3,
                "video_url": "",
                "content": "## Assigning Twilio Phone Numbers\n\nEvery sales rep should have their own dedicated Twilio number. This number is what customers text — it routes directly to that rep's inbox.\n\n### Number Pool\nWhen a rep is deactivated, their number goes into the pool. Managers can reassign it to a new hire.",
                "steps": [
                    "Go to Hub → Set Up → Phone Numbers",
                    "Tap 'Search & Purchase' — enter area code or search by pattern (e.g. 801)",
                    "Select a number and tap Purchase ($1.15/month)",
                    "Tap the number row → 'Assign to User' → search for the rep → confirm",
                    "Verify by going to the rep's profile — their Twilio Number should now show",
                    "Test it: send a text to the number from your personal phone — it should appear in their Inbox",
                ],
            },
            {
                "slug": "setup-shared-inboxes",
                "title": "Configuring Shared Inboxes",
                "description": "Create team inboxes that multiple reps share — for lead pools, support lines, and website leads.",
                "icon": "mail",
                "duration": "5 min",
                "order": 4,
                "video_url": "",
                "content": "## Configuring Shared Inboxes\n\nShared inboxes allow multiple reps to monitor and respond from a single phone number. Ideal for lead lines, support queues, or website demo request routing.",
                "steps": [
                    "Go to Hub → Set Up → Shared Inboxes",
                    "Tap '+' to create a new inbox — enter name, phone number (from your Twilio inventory), description",
                    "Tap the edit (pencil) icon → assign team members who should see this inbox",
                    "To receive website demo requests: edit the inbox → toggle 'Receive Website Leads' ON → Save",
                    "To set VA automation: edit → VA Profile → select from VA Library",
                    "To get the webhook URL for external forms: tap the link icon on the inbox card",
                ],
            },
            {
                "slug": "setup-lead-sources",
                "title": "Configuring Lead Sources",
                "description": "Set up ADF/XML webhooks, internet lead routing, and automated intake workflows.",
                "icon": "megaphone",
                "duration": "8 min",
                "order": 5,
                "video_url": "",
                "content": "## Configuring Lead Sources\n\nLead Sources connect I'm On Social to your CRM, website, or dealer portals (Cars.com, AutoTrader, OEM). Every lead gets auto-texted and reps get notified instantly.\n\n### Assignment Methods\n- **Jump Ball** — All assigned reps get notified; first to claim gets the lead\n- **Round Robin** — Leads distributed evenly in rotation\n- **Weighted Round Robin** — Distribution weighted by rep capacity",
                "steps": [
                    "Go to Hub → Set Up → Lead Source Config",
                    "Tap '+' to create a new source — enter name, assignment method, team",
                    "Copy the Webhook URL and ADF Email address — provide these to your CRM or dealer portal",
                    "Open the source → scroll to 'Workflow Automation'",
                    "Write your intake text using merge fields: 'Hi {{first_name}}, saw you were interested in a {{vehicle}} — this is [Rep Name] at [Dealership]!'",
                    "Add reps to 'Workflow Reps' — these people get notified and can claim leads",
                    "Toggle 'Enable AI Auto-Reply (Jessi)' ON if VA should handle initial conversation",
                    "Select a VA Profile from the dropdown if you have one configured",
                    "Test by submitting a lead via the ADF test tool at the bottom of the page",
                ],
            },
            {
                "slug": "setup-va-library",
                "title": "Building a Virtual Assistant (VA) Profile",
                "description": "Create AI personas that handle conversations in the rep's voice.",
                "icon": "person-circle",
                "duration": "8 min",
                "order": 6,
                "video_url": "",
                "content": "## Building a Virtual Assistant (VA) Profile\n\nVA Profiles are AI personas that respond to customers exactly like a real rep would — same tone, same style, same knowledge. They live in the VA Library and can be assigned to any Lead Source or Shared Inbox.\n\n### Key Rules\n- The VA never admits to being an AI\n- It immediately escalates when asked about specific inventory, pricing, scheduling, or trade-ins ('You're Needed' alert fires)\n- Customize the prompt per Lead Source for context-specific behavior",
                "steps": [
                    "Go to Hub → Settings → Virtual Assistant",
                    "Complete the AI Clone Profile (5 steps): bio, communication style, tools, key phrases",
                    "Navigate to Hub → Set Up → VA Library (Admin only)",
                    "Tap '+' to create a new VA Profile — name it, add tagline and custom prompt",
                    "Assign the VA to a Lead Source: Hub → Lead Source Config → open source → Workflow → select VA Profile",
                    "Test the VA: send a test lead and reply to the intake text — the VA should respond automatically",
                    "Monitor: Hub → Inbox → filter to 'AI Active' tab — see all AI-handled conversations",
                ],
            },
            {
                "slug": "setup-agent-scheduling",
                "title": "Agent Scheduling & Quiet Hours",
                "description": "Configure rep work schedules so leads only route to on-shift reps.",
                "icon": "time",
                "duration": "4 min",
                "order": 7,
                "video_url": "",
                "content": "## Agent Scheduling & Quiet Hours\n\nWhen a rep sets their schedule, the system only routes lead notifications and push alerts to reps who are currently on shift. Off-shift reps won't be woken up by a 2am lead — but the lead is never dropped.",
                "steps": [
                    "Each rep goes to Hub → Settings → My Schedule",
                    "Toggle 'Respect My Schedule' ON",
                    "Tap each day to set hours — tap 'Add Shift' for split shifts",
                    "Use Quick Presets (Mon–Fri 9–5) to set common patterns fast",
                    "For rotating schedules: toggle 'Rotating Schedule' ON → set Week A and Week B hours",
                    "To mark yourself available outside your schedule: tap '+ Override' → choose duration",
                    "Admins can view team availability: Hub → Set Up → Team Availability",
                ],
            },
            {
                "slug": "setup-integrations",
                "title": "Verifying Integrations (Stripe, Resend, Twilio)",
                "description": "Check that all third-party integrations are live and working.",
                "icon": "git-network",
                "duration": "5 min",
                "order": 8,
                "video_url": "",
                "content": "## Verifying Integrations\n\nBefore going live with a new account, verify the three core integrations are working.",
                "steps": [
                    "Twilio: Hub → Account Management → Admin Dashboard → scroll to Phone Numbers → verify Status shows 'LIVE (A2P 10DLC)'",
                    "Twilio SMS test: Hub → Admin Dashboard → Phone Numbers → 'Send Test SMS' button → enter a real number → confirm delivery",
                    "Resend Email: Submit a test demo form at imonsocial.com → confirm email arrives at sales@imonsocial.com",
                    "Stripe: Hub → Billing → create a test quote → accept it → confirm Stripe checkout session is generated",
                    "Push Notifications: Hub → Settings → Push Notifications → tap to enable in browser → Hub → Admin Dashboard → send a test push",
                    "If any integration shows errors: Hub → Admin Dashboard → System Logs → filter by category",
                ],
            },
        ],
    },

    # ─── 2. CUSTOMER SUPPORT PLAYBOOK ────────────────────────────────────────
    {
        "slug": "support-playbook",
        "title": "Customer Support Playbook",
        "description": "How to handle support requests, troubleshoot common issues, escalate correctly, and keep users unblocked fast.",
        "icon": "headset",
        "color": "#34C759",
        "roles": ["super_admin", "org_admin", "admin", "store_manager"],
        "order": 11,
        "lessons": [
            {
                "slug": "support-triage",
                "title": "Support Triage — Levels & Escalation Path",
                "description": "How to classify support requests and know when to escalate.",
                "icon": "layers",
                "duration": "4 min",
                "order": 1,
                "video_url": "",
                "content": "## Support Triage — Levels & Escalation Path\n\n### Severity Levels\n- **P0 Critical** — Platform down, can't log in, all SMS failing, data loss. Resolve in 1 hour.\n- **P1 High** — Core feature broken for a specific user (inbox not loading, campaign stuck). Resolve same day.\n- **P2 Medium** — Non-critical feature issue, confusing UI. Resolve within 48 hours.\n- **P3 Low** — Feature request, cosmetic issue. Add to backlog.\n\n### Escalation Path\n1. You → fix it using the playbooks in this training\n2. You can't fix it → escalate to Forest via direct message with error details\n3. Needs code change → Forest escalates to development",
                "steps": [
                    "Receive support request (email, text, or in-app)",
                    "Classify severity: P0 / P1 / P2 / P3",
                    "For P0/P1: notify Forest immediately, begin troubleshooting",
                    "Check System Logs: Hub → Admin Dashboard → System Logs",
                    "Document what you tried and the error message",
                    "If unresolved in 30 min: escalate with full details (user email, steps to reproduce, error screenshot)",
                ],
            },
            {
                "slug": "support-login-issues",
                "title": "Troubleshooting Login Issues",
                "description": "Fix the most common login failures — wrong password, iOS PWA issues, service worker problems.",
                "icon": "lock-open",
                "duration": "6 min",
                "order": 2,
                "video_url": "",
                "content": "## Troubleshooting Login Issues\n\n### Most Common Causes\n1. Wrong password (especially on mobile)\n2. iOS PWA service worker caching an old/broken version\n3. Account not yet activated (pending status)\n4. Session storage cleared by iOS",
                "steps": [
                    "Step 1 — Verify account exists: Hub → Account Management → All Users → search by email",
                    "Step 2 — Check account status: it should say 'active' not 'pending' or 'deactivated'",
                    "Step 3 — Reset password: open the user → tap 'Reset Password' → send them the reset email",
                    "Step 4 — If iOS PWA issue: send user to app.imonsocial.com/fix.html — this clears the service worker cache",
                    "Step 5 — If 'Connection error' on mobile: ask if this is the PWA (added to home screen). If yes, clear cache via fix.html",
                    "Step 6 — If account shows onboarding_complete: false but user is set up, impersonate and manually complete onboarding",
                ],
            },
            {
                "slug": "support-sms-issues",
                "title": "Troubleshooting SMS Not Sending",
                "description": "Diagnose and fix SMS delivery failures — Twilio errors, opt-outs, number issues.",
                "icon": "chatbubble-ellipses",
                "duration": "6 min",
                "order": 3,
                "video_url": "",
                "content": "## Troubleshooting SMS Not Sending\n\n### Common Causes\n1. Contact has opted out (sent STOP)\n2. Phone number is not in E.164 format\n3. Twilio number is not assigned to the rep\n4. Messaging Service SID misconfigured\n5. Message contains carrier-filtered content",
                "steps": [
                    "Check System Logs: Hub → Admin Dashboard → System Logs → filter by 'twilio'",
                    "Check if contact opted out: open the contact → check 'opted_out' status → if yes, they need to text START",
                    "Check phone number format: E.164 = +1XXXXXXXXXX — normalize in the contact's profile",
                    "Verify rep's Twilio number: Hub → Set Up → Phone Numbers → confirm number is assigned",
                    "Send a test SMS: Hub → Phone Numbers → 'Send Test SMS' → confirm LIVE status",
                    "If error shows '30007' or '30003': carrier filtered — rewrite message to be more personal, less promotional",
                    "If error shows '21211': invalid number — verify the phone number with the customer",
                ],
            },
            {
                "slug": "support-ai-issues",
                "title": "Troubleshooting AI (Jessi) Issues",
                "description": "Fix VA not responding, AI sending wrong messages, or escalation not triggering.",
                "icon": "sparkles",
                "duration": "5 min",
                "order": 4,
                "video_url": "",
                "content": "## Troubleshooting AI (Jessi) Issues\n\n### AI Not Responding\n- Check if AI mode is enabled on the conversation (Inbox → thread → AI mode toggle)\n- Check if the rep manually turned AI off\n\n### AI Sent a Wrong Message\n- The VA prompt may need tuning\n- Check if the outgoing message was auto-sent vs queued",
                "steps": [
                    "Open the conversation in Inbox → verify AI mode shows 'Auto' or 'Assist' not 'Human'",
                    "Check the AI Reply Queue: Hub → Admin Dashboard → System Logs → filter 'ai_reply'",
                    "If VA is not escalating hot topics: verify the Lead Source has the VA Profile assigned",
                    "If VA admitted to being AI: the VA prompt needs updating — Hub → VA Library → edit the VA → update the prompt to include 'Never admit to being AI or automated'",
                    "To disable AI for a specific conversation: open thread → tap the AI mode pill → switch to 'Human'",
                    "If AI sent spam/off-brand content: contact Forest immediately — this is P1",
                ],
            },
            {
                "slug": "support-campaign-issues",
                "title": "Troubleshooting Campaign & Task Issues",
                "description": "Fix stuck campaigns, tasks that won't complete, and enrollment problems.",
                "icon": "rocket",
                "duration": "5 min",
                "order": 5,
                "video_url": "",
                "content": "## Troubleshooting Campaign & Task Issues\n\n### Tasks Reappearing After Completion\nThis is a known pattern — the campaign scheduler can re-create tasks if they aren't properly completed. Use the steps below.\n\n### Campaign Not Sending\nCampaigns queue up steps 15-30 minutes ahead. If a step hasn't sent after 1 hour, it may be stuck.",
                "steps": [
                    "Task keeps coming back: open the contact → Campaigns tab → find enrollment → check status",
                    "If enrollment status is 'active' but task is done: tap 'Remove Campaign' to cleanly cancel",
                    "Campaign step not sending: Hub → Admin Dashboard → Scheduler → check 'campaign_step_processor' last run time",
                    "To manually trigger: Hub → Admin Dashboard → Scheduler → 'Trigger Campaign Steps Now'",
                    "Contact opted out mid-campaign: campaign will auto-pause — check contact's opted_out flag",
                    "Campaign sends wrong name: the merge field {{first_name}} defaults to 'there' if contact has no first name — add the contact's name",
                ],
            },
            {
                "slug": "support-system-logs",
                "title": "Reading System Logs",
                "description": "Use the System Logs page to diagnose backend errors without developer access.",
                "icon": "terminal",
                "duration": "4 min",
                "order": 6,
                "video_url": "",
                "content": "## Reading System Logs\n\nSystem Logs capture every error, warning, and key event from the backend. You can find and diagnose most issues here without needing to contact a developer.\n\n### Log Categories\n- **twilio** — SMS/voice errors\n- **ai_reply** — VA and AI response errors\n- **lead_intake** — Lead routing and ADF processing\n- **auth** — Login and authentication events\n- **scheduler** — Background job status",
                "steps": [
                    "Go to Hub → Admin Dashboard → System Logs",
                    "Use the filter dropdown to select a category (twilio, ai_reply, etc.)",
                    "Look at the 'level' — ERROR means something failed, WARNING is a concern but not a failure",
                    "The 'message' field contains the error — copy it for escalation",
                    "The 'details' field has the full stack trace — share with Forest for P0/P1 issues",
                    "System logs auto-clear after 30 days — screenshot any critical errors for the record",
                ],
            },
        ],
    },

    # ─── 3. ACCOUNT ONBOARDING ────────────────────────────────────────────────
    {
        "slug": "account-onboarding",
        "title": "Account Onboarding",
        "description": "Complete step-by-step walkthrough for onboarding a new client from signed quote to live platform — in under 48 hours.",
        "icon": "rocket",
        "color": "#FF9500",
        "roles": ["super_admin", "org_admin", "admin", "store_manager"],
        "order": 12,
        "lessons": [
            {
                "slug": "onboard-pre-checklist",
                "title": "Pre-Onboarding Checklist",
                "description": "What to gather from the client before you start building their account.",
                "icon": "clipboard",
                "duration": "3 min",
                "order": 1,
                "video_url": "",
                "content": "## Pre-Onboarding Checklist\n\nCollect these from the client BEFORE logging into the platform. Missing info mid-setup causes delays.",
                "steps": [
                    "Business legal name and DBA (doing business as)",
                    "Physical address, phone number, and business hours",
                    "Number of sales reps (for Twilio number count)",
                    "Email addresses for all team members to be added",
                    "Preferred area code(s) for Twilio phone numbers",
                    "Their CRM or dealer portal name (for lead source webhook setup)",
                    "Profile photos for each rep (or confirm they'll upload themselves)",
                    "Billing contact email and payment method for Stripe setup",
                ],
            },
            {
                "slug": "onboard-create-account",
                "title": "Creating the Account",
                "description": "Create the organization, store, and super admin user.",
                "icon": "add-circle",
                "duration": "5 min",
                "order": 2,
                "video_url": "",
                "content": "## Creating the Account\n\nEvery client gets one Organization containing one or more Stores. The Organization owner gets org_admin role.",
                "steps": [
                    "Log in as your super_admin account",
                    "Hub → Account Management → Organizations → '+ New Organization'",
                    "Enter legal business name, address, timezone (critical for after-hours lead timing), business hours",
                    "Tap 'Create Organization' → open it → tap 'Add Store' → fill in store details",
                    "Go to Hub → Pending Users — check if the client already submitted a signup request; if yes, approve and assign to this org",
                    "If no pending user: Hub → Team Members → Invite → enter client's email as org_admin",
                    "Open the new user → assign Organization and Store",
                    "Confirm client can log in and sees their empty dashboard",
                ],
            },
            {
                "slug": "onboard-numbers",
                "title": "Purchasing & Assigning Phone Numbers",
                "description": "Get Twilio numbers for every rep on the team.",
                "icon": "call",
                "duration": "5 min",
                "order": 3,
                "video_url": "",
                "content": "## Purchasing & Assigning Phone Numbers\n\nBuy one Twilio number per sales rep. Use local area codes for better answer rates.",
                "steps": [
                    "Hub → Set Up → Phone Numbers → 'Search & Purchase'",
                    "Enter the desired area code → browse available numbers → select one with a good local prefix",
                    "Repeat for each rep on the team",
                    "Once purchased, tap each number → 'Assign to User' → select the rep",
                    "Confirm assignment: go to that rep's profile → their Twilio Number field should be populated",
                    "Test each number: text it from a personal phone → message should appear in that rep's Inbox within seconds",
                ],
            },
            {
                "slug": "onboard-lead-sources",
                "title": "Setting Up Lead Sources",
                "description": "Connect their CRM, dealer portal, and website to automatically receive and respond to leads.",
                "icon": "git-merge",
                "duration": "8 min",
                "order": 4,
                "video_url": "",
                "content": "## Setting Up Lead Sources\n\nThis is the highest-value step. When a lead arrives from Cars.com or their website, I'm On Social fires an instant text, notifies the right reps, and Jessi starts the conversation — all automatically.",
                "steps": [
                    "Hub → Set Up → Lead Source Config → '+ New Source'",
                    "Name it (e.g. 'Cars.com', 'Website Form', 'AutoTrader')",
                    "Set assignment method: Jump Ball for small teams, Round Robin for larger teams",
                    "Copy the ADF Email address → provide to their CRM/portal's lead delivery settings",
                    "Copy the Webhook URL → provide to their website developer for form submissions",
                    "Write the intake text (this fires immediately when a lead arrives):\n  'Hi {{first_name}}! Thanks for your interest in the {{vehicle}}. This is [Rep Name] at [Dealership] — I'd love to help you find the right fit. What questions do you have?'",
                    "Add reps to the workflow: these people get notified and can claim leads",
                    "Enable AI Auto-Reply and assign a VA Profile",
                    "Submit a test lead → verify intake text arrives on test phone → confirm rep notification fires",
                ],
            },
            {
                "slug": "onboard-va-setup",
                "title": "Building the Client's VA Profile",
                "description": "Create an AI persona that speaks in the dealership's voice.",
                "icon": "person-circle",
                "duration": "6 min",
                "order": 5,
                "video_url": "",
                "content": "## Building the Client's VA Profile\n\nThe VA Profile is what makes Jessi sound like a real rep, not a bot. Invest 10 minutes here and you'll have an AI that sounds completely natural.",
                "steps": [
                    "Hub → Set Up → VA Library → '+ New VA Profile'",
                    "Name: use a real first name (e.g. 'Ashley', 'Mike') — not 'Jessi' or 'AI'",
                    "Tagline: short description like 'Sales Consultant at [Dealership Name]'",
                    "System prompt: include — dealership name, rep's personality style, what they sell, what they DON'T do (never discuss specific pricing without checking inventory first, never admit to being automated)",
                    "Sample prompt: 'You are Ashley, a friendly sales consultant at Best Ford in Provo UT. You help customers find the right Ford vehicle. When asked about specific pricing, availability, or to schedule, say you'll check on that and get back to them shortly. Always stay warm, conversational, and under 2 sentences per reply.'",
                    "Assign to Lead Sources: go to each Lead Source → Workflow section → VA Profile dropdown → select the new VA",
                    "Test: submit a lead → reply to the intake text → verify VA responds naturally",
                ],
            },
            {
                "slug": "onboard-profiles",
                "title": "Rep Profile & Digital Card Setup",
                "description": "Ensure every rep has a complete profile before go-live.",
                "icon": "id-card",
                "duration": "5 min",
                "order": 6,
                "video_url": "",
                "content": "## Rep Profile & Digital Card Setup\n\nEvery rep's public-facing profile (digital card, link page) needs to be complete before they start using the platform. Customers will see this.",
                "steps": [
                    "Each rep: Hub → My Account → tap 'Edit Profile'",
                    "Upload professional headshot (400x400px minimum, face centered)",
                    "Fill in: title, bio (2-3 sentences about them personally), phone, email",
                    "Add social links if they have them (Facebook, Instagram, LinkedIn)",
                    "Check the Digital Card: Hub → My Presence → tap Digital Card → view public page",
                    "Check the Link Page: Hub → My Presence → tap Link Page",
                    "Admins: verify using impersonation — Hub → All Users → impersonate each rep → check their profile",
                ],
            },
            {
                "slug": "onboard-golive",
                "title": "Go-Live Checklist",
                "description": "Final verification steps before the client starts using the platform live.",
                "icon": "checkmark-circle",
                "duration": "5 min",
                "order": 7,
                "video_url": "",
                "content": "## Go-Live Checklist\n\nRun through this checklist on the day of launch to confirm everything is working before the client starts using it for real.",
                "steps": [
                    "☐ All rep profiles have photos and complete bios",
                    "☐ Every rep has a Twilio number assigned",
                    "☐ All lead sources are created and webhook URLs sent to CRM/website",
                    "☐ Test lead submitted and received in the platform (intake text fired, rep notified)",
                    "☐ VA Profile assigned to all lead sources",
                    "☐ Each rep can log into the app and navigate the Inbox",
                    "☐ Stripe payment is configured (if billing client directly)",
                    "☐ Training assigned: each rep enrolled in 'Onboarding Videos' track in Training Hub",
                    "☐ Manager has reviewed Team Availability page",
                    "☐ First campaign is created and active for new leads",
                ],
            },
            {
                "slug": "onboard-client-training",
                "title": "Training the Client's Team",
                "description": "How to walk the client through the platform and ensure adoption.",
                "icon": "school",
                "duration": "5 min",
                "order": 8,
                "video_url": "",
                "content": "## Training the Client's Team\n\nThe best onboarding is done in 30 minutes over a Zoom call. Focus on the 3 things they'll use every day.",
                "steps": [
                    "Schedule a 30-minute Zoom call with the manager and key reps",
                    "Show them: (1) The Inbox — how to reply, use templates, and handle AI conversations",
                    "Show them: (2) Touchpoints — the daily 30-second workflow",
                    "Show them: (3) How to add a new contact and tag them",
                    "Direct them to Training Hub: Hub → Learning → Training Hub → assign 'Onboarding Videos' track",
                    "Share the iOS install instructions: open app.imonsocial.com in Safari → Share → Add to Home Screen",
                    "Schedule a 1-week follow-up check-in",
                ],
            },
        ],
    },

    # ─── 4. ACCOUNT MANAGEMENT ───────────────────────────────────────────────
    {
        "slug": "account-management",
        "title": "Account Management",
        "description": "How to manage existing client accounts — health monitoring, retention, renewals, escalations, and feature adoption.",
        "icon": "briefcase",
        "color": "#AF52DE",
        "roles": ["super_admin", "org_admin", "admin", "store_manager"],
        "order": 13,
        "lessons": [
            {
                "slug": "acct-health-dashboard",
                "title": "Reading the Account Health Dashboard",
                "description": "Use the health dashboard to spot at-risk accounts before they churn.",
                "icon": "pulse",
                "duration": "5 min",
                "order": 1,
                "video_url": "",
                "content": "## Reading the Account Health Dashboard\n\nThe Account Health dashboard shows you which accounts are thriving and which are at risk — before they cancel.\n\n### Health Score Components\n- **Login frequency** — Are reps logging in daily?\n- **Touchpoint activity** — Messages sent, contacts reached\n- **Campaign usage** — Active campaigns running\n- **Lead intake** — Leads flowing in and being claimed\n- **Feature adoption** — Which features are being used",
                "steps": [
                    "Go to Hub → Account Management → Account Health",
                    "Review the top-level stats: total accounts, avg health score, at-risk count",
                    "Filter by 'At Risk' — these need immediate attention",
                    "Click into an at-risk account to see which specific metrics are low",
                    "A low 'login frequency' = user adoption problem → schedule training call",
                    "A low 'touchpoint activity' = they aren't using the app → check if their Twilio numbers work",
                    "Document action taken: add a note to the account and set a follow-up reminder",
                ],
            },
            {
                "slug": "acct-monthly-checkin",
                "title": "Monthly Check-In Workflow",
                "description": "The standard monthly review process for every managed account.",
                "icon": "calendar",
                "duration": "5 min",
                "order": 2,
                "video_url": "",
                "content": "## Monthly Check-In Workflow\n\nEvery active account should get a monthly check-in. This keeps clients engaged, surfaces problems early, and creates upsell opportunities.",
                "steps": [
                    "Pull the account's activity report: Hub → Training Reports (for training engagement) and the account's lead intake dashboard",
                    "Check: How many leads came in this month? How many were claimed within 5 minutes?",
                    "Check: Are all reps logging in at least 3x/week?",
                    "Prepare 2-3 talking points: something they're doing well + 1 area to improve",
                    "Schedule a 15-minute call or send a personalized email summary",
                    "During the call: show them a feature they aren't using yet (campaigns, VA, team scheduling)",
                    "If contract is approaching renewal: surface the value delivered and initiate renewal conversation",
                    "Log the check-in: create a note on their account with date and outcome",
                ],
            },
            {
                "slug": "acct-churn-prevention",
                "title": "Identifying & Preventing Churn",
                "description": "Early warning signs and the process to prevent a client from leaving.",
                "icon": "warning",
                "duration": "5 min",
                "order": 3,
                "video_url": "",
                "content": "## Identifying & Preventing Churn\n\n### Early Warning Signals\n- Health score drops below 40\n- No logins in 14+ days\n- Rep turnover (key user deactivated)\n- Payment failed\n- Support tickets increasing\n- Manager changes at the client",
                "steps": [
                    "Set up weekly review: every Monday, check Account Health → sort by health score ascending",
                    "For any account below 50: reach out within 24 hours — 'Hey [Name], noticed things have been quiet — anything I can help with?'",
                    "Dig into the cause: is it the technology, adoption, or something happening at their business?",
                    "Offer a re-onboarding session for low adoption accounts",
                    "For payment failures: reach out personally within 24 hours — never let it sit",
                    "For manager/rep turnover: offer to re-train new team members at no extra cost",
                    "Document win/loss: every churn event gets a debrief note — what was the real reason?",
                ],
            },
            {
                "slug": "acct-feature-adoption",
                "title": "Feature Adoption Coaching",
                "description": "Help clients discover and use features that drive more value.",
                "icon": "star",
                "duration": "4 min",
                "order": 4,
                "video_url": "",
                "content": "## Feature Adoption Coaching\n\nMost clients use 20% of the platform. The other 80% is waiting to be discovered — and each feature unlocked makes them stickier.",
                "steps": [
                    "Check which features the account uses: Hub → Account Health → the account's feature adoption list",
                    "If they aren't using Campaigns: 'A campaign can automatically follow up with every sold customer at 30/60/90 days — want me to set one up?'",
                    "If they aren't using VA: 'Right now, when a lead comes in at midnight, no one responds. The VA can handle that instantly in your voice — interested?'",
                    "If they aren't using Shared Inboxes: 'Your manager can see all rep conversations in one place — here's how to set that up'",
                    "If they aren't using digital cards: 'Your reps can share their digital card via QR code at every delivery — it auto-collects a review'",
                    "Don't overwhelm — introduce ONE new feature per check-in",
                ],
            },
            {
                "slug": "acct-upgrade-downgrade",
                "title": "Handling Upgrades & Downgrades",
                "description": "Process for changing subscription plans, adding users, or reducing seats.",
                "icon": "trending-up",
                "duration": "4 min",
                "order": 5,
                "video_url": "",
                "content": "## Handling Upgrades & Downgrades\n\n### Upgrade (Adding Users or Upgrading Plan)\nUpgrades are revenue opportunities. Always upgrade before renewal — never let someone cancel and come back at a lower price.",
                "steps": [
                    "Upgrade request: create a new quote reflecting the new plan/user count",
                    "Go to Hub → Account Management → Quotes → '+ New Quote'",
                    "Select the client, new plan, user count → apply any promo discount",
                    "Send via 'Send Link via Text' or email → client signs digitally",
                    "After signing: Stripe checkout session generates automatically",
                    "Downgrade request: discuss value before agreeing — understand the real reason",
                    "If cost is the issue: offer a different plan tier before agreeing to downgrade",
                    "If firm on downgrade: update their subscription → reduce seat count → adjust billing",
                ],
            },
        ],
    },

    # ─── 5. BILLING & SUBSCRIPTIONS ──────────────────────────────────────────
    {
        "slug": "billing-subscriptions",
        "title": "Billing & Subscriptions",
        "description": "Complete billing operations guide — quotes, Stripe, invoices, W-9, partner commissions, and failed payment handling.",
        "icon": "card",
        "color": "#C9A962",
        "roles": ["super_admin", "org_admin", "admin"],
        "order": 14,
        "lessons": [
            {
                "slug": "billing-create-quote",
                "title": "Creating & Sending a Quote",
                "description": "Build a professional quote and send it to a prospect in under 3 minutes.",
                "icon": "document-text",
                "duration": "5 min",
                "order": 1,
                "video_url": "",
                "content": "## Creating & Sending a Quote\n\nEvery new client starts with a quote. The system auto-generates a professional PDF, handles digital signing, and creates a Stripe payment session — all automatically.",
                "steps": [
                    "Hub → Account Management → Quotes → '+ Create Quote'",
                    "Enter client information: company name, contact name, email, phone",
                    "Select plan type: Individual or Store (Store = multiple users)",
                    "For Store plan: enter number of users → pricing calculates automatically",
                    "Apply discount if applicable: enter percentage → system shows final monthly price",
                    "Add notes (e.g. 'Includes 30-day free trial') → tap 'Create Quote'",
                    "Review the quote → tap 'Send Link via Text' → enter client's phone → SMS opens pre-filled",
                    "Client receives a link to /quote/accept/[id] — they review, sign, and Stripe checkout launches automatically",
                ],
            },
            {
                "slug": "billing-stripe-payment",
                "title": "Stripe Payment Processing",
                "description": "How Stripe checkout works and what to do when a payment is set up.",
                "icon": "card",
                "duration": "4 min",
                "order": 2,
                "video_url": "",
                "content": "## Stripe Payment Processing\n\nOnce a quote is signed, Stripe handles the monthly subscription automatically. You don't need to manually charge clients.",
                "steps": [
                    "After client signs the quote, they are automatically directed to a Stripe checkout page",
                    "The checkout amount matches exactly what was on the quote — no manual entry needed",
                    "Client enters their card → Stripe creates a monthly recurring subscription",
                    "You receive a notification (email + push) when payment completes",
                    "The quote status updates to 'paid' in Hub → Quotes",
                    "To check payment status on any quote: Hub → Quotes → find quote → tap 'Payment Status'",
                    "If payment was set up but you need to verify: check Stripe Dashboard → Subscriptions",
                ],
            },
            {
                "slug": "billing-failed-payment",
                "title": "Handling Failed Payments",
                "description": "Process for outreach and resolution when a client's payment fails.",
                "icon": "alert-circle",
                "duration": "5 min",
                "order": 3,
                "video_url": "",
                "content": "## Handling Failed Payments\n\nStripe will retry failed payments automatically for 7 days. Your job is to reach out personally within 24 hours of the first failure — before it becomes an awkward conversation.\n\n### Response Time\n- Day 1 fail: personal text or call\n- Day 3: follow-up if no response\n- Day 7: Stripe cancels subscription — you need to create a new quote",
                "steps": [
                    "You receive a notification when payment fails (if Stripe webhook is configured)",
                    "Reach out same day: 'Hey [Name], looks like we had a hiccup with your billing — just wanted to make sure everything's okay on your end'",
                    "Never lead with 'your payment failed' — keep it relationship-first",
                    "If it's a card issue: send them the Stripe payment link again (from their quote in Hub → Quotes)",
                    "If they want to change payment method: they can update in their Stripe customer portal",
                    "Document the call: add a note to their account",
                    "After 7 days with no payment: subscription is cancelled in Stripe — their access continues until you manually disable",
                ],
            },
            {
                "slug": "billing-invoices",
                "title": "Invoice Management",
                "description": "Create, view, and manage invoices for partner and reseller billing.",
                "icon": "receipt",
                "duration": "4 min",
                "order": 4,
                "video_url": "",
                "content": "## Invoice Management\n\nMonthly invoices for white-label partners and resellers are generated automatically on the 1st of each month.",
                "steps": [
                    "View all partner invoices: Hub → Account Management → Partner Invoices",
                    "Invoices are auto-generated monthly — each shows amount owed, commission breakdown, and payment status",
                    "To send a specific invoice: open it → tap 'Send Invoice Email'",
                    "Partners receive invoices at their billing email address on file",
                    "For overdue invoices: follow the same outreach process as failed payments",
                    "Manual invoice creation (one-off billing): Hub → Billing → My Invoices → '+ New Invoice'",
                ],
            },
            {
                "slug": "billing-w9",
                "title": "W-9 Collection & Verification",
                "description": "Process for collecting and verifying partner W-9 forms.",
                "icon": "document",
                "duration": "3 min",
                "order": 5,
                "video_url": "",
                "content": "## W-9 Collection & Verification\n\nAll partners and resellers need a W-9 on file before receiving commission payments. The system handles collection automatically through the Partner Agreement flow.",
                "steps": [
                    "When a partner signs their agreement, they receive a W-9 upload link automatically",
                    "To check W-9 status: Hub → Account Management → Partner Agreements → filter by 'Awaiting W-9'",
                    "When a W-9 is submitted: you receive a notification — review it under their agreement detail page",
                    "To verify: open agreement → W-9 panel → review the document → tap 'Mark as Verified'",
                    "If W-9 is incomplete or incorrect: contact partner directly — send them the upload link again from their agreement page",
                    "Verified W-9 status shows a green badge on the agreement",
                ],
            },
            {
                "slug": "billing-partner-commissions",
                "title": "Partner & Reseller Commissions",
                "description": "How partner commission tiers work and how to process payouts.",
                "icon": "cash",
                "duration": "4 min",
                "order": 6,
                "video_url": "",
                "content": "## Partner & Reseller Commissions\n\n### Commission Tiers\n- **Referral Partners**: 10% first year / 15% ongoing\n- **Reseller Tier 1**: 20% of all MRR\n- **Reseller Tier 2**: 30% of all MRR\n- **Reseller Tier 3**: 40% of all MRR\n- Custom notes in the agreement override standard tiers",
                "steps": [
                    "View partner's commission tier: Hub → Partner Agreements → open agreement → Exhibit A section",
                    "Monthly invoices are auto-calculated based on tier × accounts managed",
                    "To process payout: verify W-9 is on file → confirm invoice amount → pay via bank transfer",
                    "To update a partner's tier: open their agreement → edit commission tier → both parties must re-sign",
                    "Commission disputes: pull the invoice history and account MRR — all amounts are logged",
                ],
            },
        ],
    },

    # ─── 6. TECHNICAL REFERENCE ──────────────────────────────────────────────
    {
        "slug": "technical-reference",
        "title": "Technical Reference",
        "description": "Developer and IT guide — architecture, API endpoints, database schema, Twilio webhooks, deployment, and debugging.",
        "icon": "code-slash",
        "color": "#FF3B30",
        "roles": ["super_admin"],
        "order": 15,
        "lessons": [
            {
                "slug": "tech-architecture",
                "title": "Architecture Overview",
                "description": "How the platform is built — frontend, backend, database, and hosting.",
                "icon": "layers",
                "duration": "8 min",
                "order": 1,
                "video_url": "",
                "content": "## Architecture Overview\n\n### Stack\n- **Frontend**: React Native (Expo Web) — single codebase for iOS, Android, and Web PWA\n- **Backend**: FastAPI (Python) — async, handles 100+ API routes\n- **Database**: MongoDB Atlas — document store, all data\n- **Hosting**: Emergent Platform — Kubernetes cluster, auto-scaling\n- **File Storage**: Emergent Object Storage — images, PDFs, media\n\n### Key Services\n- **Twilio** — SMS, MMS, voice calls, recordings\n- **OpenAI (via Emergent LLM Key)** — GPT-5.2 for Jessi AI, Whisper for call transcription\n- **Resend** — Transactional email delivery\n- **Stripe** — Payment processing, subscriptions\n- **APScheduler** — 11 background jobs for campaigns, tasks, reports\n\n### Repository Structure\n```\n/app\n  /backend         # FastAPI Python API\n    /routers       # One file per feature domain\n    /services      # Shared services (Twilio, etc.)\n    /scripts       # One-time migration scripts\n  /frontend        # Expo React Native app\n    /app           # File-based routing (Expo Router)\n    /components    # Shared UI components\n    /hooks         # Custom React hooks\n    /services      # API client, auth\n    /store         # Zustand state management\n```",
                "steps": [
                    "Frontend entry: /app/frontend/app/ — file-based routing, each file is a screen",
                    "Backend entry: /app/backend/server.py — registers all routers",
                    "Database access: /app/backend/routers/database.py — Motor async MongoDB client",
                    "All API routes are prefixed with /api (Kubernetes ingress rule)",
                    "Frontend calls backend via REACT_APP_BACKEND_URL env var",
                    "Never hardcode URLs — always use environment variables",
                ],
            },
            {
                "slug": "tech-api-endpoints",
                "title": "Key API Endpoints Reference",
                "description": "The most important API endpoints every developer needs to know.",
                "icon": "server",
                "duration": "8 min",
                "order": 2,
                "video_url": "",
                "content": "## Key API Endpoints Reference\n\n### Authentication\n- `POST /api/auth/login` — Login (returns token + user)\n- `GET /api/auth/me` — Get current user\n- `PATCH /api/users/{id}` — Update user profile\n\n### Contacts & Messaging\n- `GET /api/contacts/{user_id}` — List contacts\n- `POST /api/contacts` — Create contact\n- `GET /api/messages/conversations/{user_id}` — Inbox threads\n- `POST /api/messages/send` — Send SMS/MMS\n\n### Lead Intake\n- `POST /api/leads/adf` — ADF/XML lead parser\n- `POST /api/leads/webhook/{source_id}` — JSON lead webhook\n- `POST /api/demo-requests` — Website demo form submissions\n\n### Scheduling\n- `GET /api/schedule/me` — Current user's schedule\n- `PUT /api/schedule/me` — Save schedule\n- `GET /api/schedule/team` — Full team availability\n\n### Admin\n- `GET /api/admin/twilio/status` — Twilio live status\n- `POST /api/admin/twilio/test-sms` — Send test SMS\n- `GET /api/admin/system-logs` — Error logs\n- `GET /api/scheduler/status` — Background job status",
                "steps": [
                    "All endpoints require /api prefix",
                    "Auth: Bearer token in Authorization header, OR X-User-ID header for admin endpoints",
                    "Test any endpoint: copy REACT_APP_BACKEND_URL from frontend/.env",
                    "Full API documentation: Hub → Learning → API Documentation (in-app docs page)",
                ],
            },
            {
                "slug": "tech-database",
                "title": "Database Collections Reference",
                "description": "Key MongoDB collections — what they store and how they relate.",
                "icon": "server",
                "duration": "6 min",
                "order": 3,
                "video_url": "",
                "content": "## Database Collections Reference\n\n### Core Collections\n| Collection | Purpose |\n|---|---|\n| `users` | All user accounts — reps, managers, admins |\n| `contacts` | Customer contacts per user |\n| `conversations` | Inbox threads — one per contact per user |\n| `messages` | Individual messages in conversations |\n| `campaigns` | Campaign definitions |\n| `campaign_enrollments` | Which contacts are in which campaigns |\n| `campaign_pending_sends` | Pre-scheduled campaign messages (the queue) |\n\n### Lead & Analytics Collections\n| Collection | Purpose |\n|---|---|\n| `inbound_leads` | Internet lead intake records |\n| `demo_requests` | Website form submissions |\n| `contact_events` | Link clicks, card views, analytics |\n| `short_urls` | Tracked shortened URLs |\n\n### Operations Collections\n| Collection | Purpose |\n|---|---|\n| `system_logs` | Backend error logs |\n| `user_schedules` | Rep work schedule configurations |\n| `push_subscriptions` | Web push notification subscriptions |\n| `payment_transactions` | Stripe payment records |\n| `subscription_quotes` | Client quotes (signed/unsigned) |",
                "steps": [
                    "Never modify production data directly — use API endpoints",
                    "All IDs are MongoDB ObjectId (24-char hex) — use str(ObjectId) in Python",
                    "TTL indexes auto-expire: contact_events (2yr), notifications (90d), short_url_clicks (1yr)",
                    "Compound indexes on (user_id, status) for all major query paths",
                    "Multi-tenant: always filter by account_id or user_id — never query without a scope",
                ],
            },
            {
                "slug": "tech-twilio-webhooks",
                "title": "Twilio Webhook Configuration",
                "description": "How Twilio webhooks work and how to verify/fix them.",
                "icon": "git-network",
                "duration": "5 min",
                "order": 4,
                "video_url": "",
                "content": "## Twilio Webhook Configuration\n\nTwilio calls our backend when events happen (inbound SMS, call completed, recording ready). These webhooks must be configured correctly or features silently fail.\n\n### Webhook URLs\n- Inbound SMS/MMS: `{APP_URL}/api/webhooks/twilio/incoming`\n- Inbound Voice: `{APP_URL}/api/webhooks/twilio/voice`\n- Call Bridge: `{APP_URL}/api/webhooks/twilio/call-bridge`\n- Recording Complete: `{APP_URL}/api/webhooks/twilio/recording-complete`\n- Stripe Payments: `{APP_URL}/api/webhook/stripe`",
                "steps": [
                    "Auto-configuration: on every server start, the app checks and fixes Twilio webhook URLs automatically",
                    "To manually verify: Hub → Admin Dashboard → Phone Numbers → any number row → check 'Webhook Status'",
                    "To fix a number's webhook: Phone Numbers → number → '⚙ Fix Webhook' button",
                    "STOP/UNSTOP/HELP: handled automatically in twilio_webhooks.py — no configuration needed",
                    "Voice bridge: when a rep calls a customer, Twilio bridges the call and plays a whisper announcement",
                    "Recording: all calls are recorded and transcribed via Whisper API — stored on the contact's Calls tab",
                ],
            },
            {
                "slug": "tech-deployment",
                "title": "Deploying Code Changes",
                "description": "How to deploy updates from preview to production.",
                "icon": "cloud-upload",
                "duration": "4 min",
                "order": 5,
                "video_url": "",
                "content": "## Deploying Code Changes\n\nThe platform has two environments:\n- **Preview** (dev): Changes are made here, tested here\n- **Production** (`app.imonsocial.com`): What clients use — only deploy after full testing",
                "steps": [
                    "Make and test changes in the preview environment first",
                    "Verify backend is healthy: curl {PREVIEW_URL}/api/health",
                    "Take a screenshot of the affected UI to confirm no regressions",
                    "In the Emergent chat: tap the Deploy button (or say 'deploy to production')",
                    "Wait for deployment to complete (~2-3 minutes)",
                    "Verify production: open app.imonsocial.com in a new browser tab → confirm changes are live",
                    "NEVER push breaking changes on Friday afternoon or Monday morning (peak usage)",
                    "If something breaks in production: use the Rollback feature in Emergent to instantly revert",
                ],
            },
            {
                "slug": "tech-debugging",
                "title": "Common Debug Patterns",
                "description": "The fastest ways to diagnose and fix backend issues.",
                "icon": "bug",
                "duration": "6 min",
                "order": 6,
                "video_url": "",
                "content": "## Common Debug Patterns\n\n### Checking Backend Logs (Preview Only)\n```bash\ntail -n 50 /var/log/supervisor/backend.err.log\n```\n\n### Testing an API Endpoint\n```bash\nAPI_URL=$(grep REACT_APP_BACKEND_URL /app/frontend/.env | cut -d= -f2)\ncurl -s $API_URL/api/health\n```\n\n### Backend Won't Start?\n```bash\nsudo supervisorctl status backend\ntail -n 20 /var/log/supervisor/backend.err.log\n```",
                "steps": [
                    "Backend crashing: tail -n 30 /var/log/supervisor/backend.err.log — look for SyntaxError, ImportError, NameError",
                    "Frontend not updating: sudo supervisorctl restart frontend — force recompile",
                    "Check if a feature endpoint exists: curl -s {API_URL}/api/{endpoint} | head -20",
                    "SLOW REQUEST warnings in logs: request took >2s — check for N+1 DB queries",
                    "MongoDB ObjectId errors: make sure you're using str(ObjectId(id)) not raw id strings",
                    "Import errors after adding a new file: ensure file is imported in server.py's router list",
                    "The 'safe' test: always curl /api/health first — if that fails, the whole backend is down",
                ],
            },
            {
                "slug": "tech-manage-training",
                "title": "Adding & Editing Training Content",
                "description": "How to add new lessons, update content, and manage training tracks as an admin.",
                "icon": "create",
                "duration": "4 min",
                "order": 7,
                "video_url": "",
                "content": "## Adding & Editing Training Content\n\nTraining content is fully editable through the in-app admin interface — no code changes needed for content updates.",
                "steps": [
                    "Go to Hub → Learning → Manage Training",
                    "To edit a track: tap the pencil icon → change title, description, color, or which roles can see it → Save",
                    "To add a new lesson: tap a track → tap '+ Add Lesson' → fill in title, description, steps, video URL",
                    "For video URL: paste the full YouTube URL (e.g. https://www.youtube.com/watch?v=xxxxx)",
                    "To reorder lessons: drag the handle (≡) next to a lesson up or down",
                    "To delete a lesson: swipe left on the lesson row → tap Delete",
                    "To create a new track: scroll to bottom → '+ New Track' → fill in details → assign roles",
                    "After adding content, go to Training Hub to verify it displays correctly",
                ],
            },
        ],
    },

    # ─── 7. SALES PROCESS ────────────────────────────────────────────────────
    {
        "slug": "sales-process",
        "title": "Sales Process",
        "description": "How to sell I'm On Social — from first conversation to signed deal. Includes demo flow, objection handling, and the close process.",
        "icon": "trending-up",
        "color": "#FF2D55",
        "roles": ["super_admin", "org_admin", "admin", "store_manager", "user"],
        "order": 16,
        "lessons": [
            {
                "slug": "sales-value-prop",
                "title": "The I'm On Social Value Proposition",
                "description": "What problems we solve and who our ideal customer is.",
                "icon": "bulb",
                "duration": "4 min",
                "order": 1,
                "video_url": "",
                "content": "## The I'm On Social Value Proposition\n\n### The Core Problem We Solve\nSales professionals (especially in automotive) spend thousands on leads but lose them because follow-up is slow, inconsistent, and impersonal. Customers buy from people they trust — but building trust at scale is impossible manually.\n\n### What We Do\nI'm On Social gives every rep an AI clone (Jessi) that responds to leads instantly, in their exact voice — while they're with another customer, sleeping, or off shift. When a hot topic comes up (price, availability, scheduling), the AI hands off to the human rep immediately.\n\n### The Numbers\n- Average lead response time industry: 47 hours\n- Our average response time: 30 seconds\n- Leads contacted within 5 minutes: 21× more likely to convert",
                "steps": [
                    "Lead with the outcome: 'Most dealerships lose 60% of their internet leads because they never respond fast enough — we fix that'",
                    "Use the 3-second pitch: 'Jessi responds to every lead instantly in your rep's voice, 24/7, and calls the rep the moment a customer is ready to buy'",
                    "Ideal customer: 3-20 rep dealerships, real estate offices, insurance agencies, home services — any business that follows up with leads",
                    "Problem/Agitate/Solve: describe the pain → make it feel real → show how we solve it",
                ],
            },
            {
                "slug": "sales-discovery",
                "title": "Discovery Conversation",
                "description": "The questions to ask to qualify a prospect and understand their pain.",
                "icon": "search",
                "duration": "5 min",
                "order": 2,
                "video_url": "",
                "content": "## Discovery Conversation\n\nBefore you demo anything, understand their world. A 10-minute discovery call saves a 45-minute demo for the wrong prospect.\n\n### The 5 Discovery Questions\n1. 'How are you currently following up with leads — what does that process look like?'\n2. 'What's your biggest frustration with lead follow-up right now?'\n3. 'How many leads do you get per month? How many do you actually contact within 24 hours?'\n4. 'Do your reps do their own texting, or is there a BDC?'\n5. 'What would it mean for your business if you doubled your lead contact rate?'",
                "steps": [
                    "Start with rapport — 3 minutes of personal connection before any pitch",
                    "Ask question 1 — listen fully, don't interrupt, take mental notes",
                    "Reflect back: 'So it sounds like the main challenge is [X] — is that right?'",
                    "Ask question 3 — the lead volume/contact rate gap is usually the biggest aha moment",
                    "If they say 'we contact every lead' — ask 'within how many minutes?'",
                    "Qualify: do they have 3+ reps? Do they have a texting number? Do they get at least 20 leads/month?",
                    "If qualified: 'Let me show you exactly how we solve [their specific pain] — is 20 minutes good?'",
                ],
            },
            {
                "slug": "sales-demo-flow",
                "title": "Demo Flow — What to Show & In What Order",
                "description": "The 20-minute demo sequence that closes deals.",
                "icon": "play",
                "duration": "6 min",
                "order": 3,
                "video_url": "",
                "content": "## Demo Flow — What to Show & In What Order\n\n### The Rule\nOnly show features that solve the pain they told you about in discovery. Don't do a feature tour — do a solution tour.\n\n### Demo Sequence (20 minutes)\n1. **The Lead Comes In** (3 min) — Submit a live test lead → show the instant intake text → show rep notification\n2. **Jessi Handles It** (4 min) — Show AI responding naturally → show hot-topic escalation → 'You're Needed' alert\n3. **Rep Takes Over** (3 min) — Show the Inbox → reply in the thread → use a template\n4. **The Campaign Runs** (3 min) — Show a drip campaign → 30-day / 60-day follow-ups\n5. **The Dashboard** (3 min) — Touchpoints, performance, account health\n6. **The Close** (4 min) — Pricing, next steps, handle objections",
                "steps": [
                    "Open with: 'I'm going to show you what happens when a lead comes in right now — starting with a real live test'",
                    "Submit a test lead during the demo — this is always memorable",
                    "When the intake text fires: 'That just went to your rep's phone AND Jessi started the conversation automatically'",
                    "Show the inbox thread — make it personal to their business (use their actual business name if possible)",
                    "The campaign demo: 'Even if this customer doesn't buy today, in 30 days they get this message automatically — still in [Rep Name]'s voice'",
                    "Don't oversell — if they're nodding, move to the close",
                ],
            },
            {
                "slug": "sales-objections",
                "title": "Handling Objections",
                "description": "The 5 most common objections and how to respond.",
                "icon": "shield",
                "duration": "5 min",
                "order": 4,
                "video_url": "",
                "content": "## Handling Objections\n\n### The 5 Common Objections\n\n**'It's too expensive'**\nResponse: 'What are you paying right now for leads? If this turns one extra lead per month into a sale, what's that worth to you? Most dealers close 1-2 more per month — that's well worth [price].'\n\n**'We already have a BDC / CRM'**\nResponse: 'This isn't a replacement — it fills the gap between your CRM and actual human conversation. [BDC name] can't text a customer at 11pm and sound like Mike. We can.'\n\n**'We need to think about it'**\nResponse: 'Totally fair. What specifically do you want to think through? I'd rather address it now than have you wonder later.' Then be quiet.\n\n**'Can we start next month?'**\nResponse: 'Every month you wait is leads going unanswered. I can have you live in 48 hours — what's holding us back from today?'\n\n**'The reps won't use it'**\nResponse: 'The reps don't have to do anything differently — Jessi handles the first response automatically. The rep only steps in when a customer is hot. We actually get more rep engagement because every notification is a warm lead.'",
                "steps": [
                    "Never argue with an objection — acknowledge it first: 'That's a fair question'",
                    "Use the Feel/Felt/Found: '[Name], I understand how you feel — a lot of our clients felt the same way. What they found was...'",
                    "After handling an objection, always ask: 'Does that make sense? / Does that address your concern?'",
                    "If they repeat the same objection twice — it's the real objection. Dig deeper: 'What would need to be true for this to make sense for you?'",
                    "Price objections: always anchor to value, not cost",
                ],
            },
            {
                "slug": "sales-close",
                "title": "Creating & Sending the Quote to Close",
                "description": "How to move from demo to signed quote in the same conversation.",
                "icon": "checkmark-done",
                "duration": "5 min",
                "order": 5,
                "video_url": "",
                "content": "## Creating & Sending the Quote to Close\n\n### The Best Close Is a Quote They Can Sign Right Now\nDon't email a PDF and wait. Create the quote live, send them the link via text, and walk them through signing while you're on the call.",
                "steps": [
                    "After handling objections: 'Based on what you told me, the [plan] plan at $[X]/month makes the most sense for your team. Let me pull that up right now.'",
                    "Hub → Quotes → '+ New Quote' — fill in their details as they watch (screen share if on Zoom)",
                    "Ask: 'What email should I send this to?' — personalization creates urgency",
                    "Tap 'Send Link via Text' → enter their mobile number → they receive the link in 5 seconds",
                    "'While you're on the phone with me — can you open that text? I'll walk you through it.'",
                    "Guide them through: review the plan → type their name as signature → tap Accept",
                    "After they sign: 'Perfect. You'll get a Stripe link to set up billing — that takes 2 minutes and you're live. I'll have your account set up within 48 hours.'",
                ],
            },
            {
                "slug": "sales-follow-up",
                "title": "Follow-Up Cadence After Demo",
                "description": "What to do after a demo that didn't close — structured follow-up without being annoying.",
                "icon": "calendar",
                "duration": "4 min",
                "order": 6,
                "video_url": "",
                "content": "## Follow-Up Cadence After Demo\n\nMost deals close on the 5th–7th contact. Here's the exact follow-up sequence for prospects who don't sign during the demo.",
                "steps": [
                    "Day 0 (same day): Send the quote link via text with a personal message: 'Great talking today [Name]! Here's the quote from our conversation — let me know if you have any questions.'",
                    "Day 1: Email a 1-sentence recap + the value from their specific discovery (reference what they told you)",
                    "Day 3: Text: 'Hey [Name], just checking in — any questions on the quote? Happy to jump on a quick call.'",
                    "Day 7: Use I'm On Social itself — create them as a contact, tag 'prospect', enroll in a 7-day drip (ironic, shows the product works)",
                    "Day 14: Personal video message or call — reference something they said in the demo",
                    "Day 30: One final reach-out: 'Still thinking about you — when you're ready, we're here. What's changed since we last spoke?'",
                    "If no response after Day 30: move to a monthly touch and revisit in 90 days",
                ],
            },
            {
                "slug": "sales-referrals",
                "title": "Referrals & Account Expansion",
                "description": "How to get referrals from happy clients and expand seats within accounts.",
                "icon": "people",
                "duration": "4 min",
                "order": 7,
                "video_url": "",
                "content": "## Referrals & Account Expansion\n\nThe best leads come from happy customers. Here's when and how to ask.",
                "steps": [
                    "Best time to ask for referral: 30 days after go-live — when they've seen real results",
                    "Script: '[Name], you mentioned last month you were closing more leads — who else in your network would benefit from this same result?'",
                    "Always personalize: 'I noticed you're connected to [Name] at [Dealership] — would you be comfortable making an introduction?'",
                    "Create a contact card for the referral and tag them 'Referred by [Client Name]'",
                    "Expansion — add users: 'You added 2 new reps last month — do they all have numbers assigned? I can have them set up in 20 minutes.'",
                    "Expansion — upgrade plan: at quarterly check-in, review which features they aren't using — each unused feature is a conversation about an upgraded plan",
                ],
            },
        ],
    },

    # ─── 8. MARKETING PLAYBOOK ───────────────────────────────────────────────
    {
        "slug": "marketing-playbook",
        "title": "Marketing Playbook",
        "description": "How to market I'm On Social — website leads, social proof, content strategy, partner co-marketing, and analytics.",
        "icon": "megaphone",
        "color": "#5856D6",
        "roles": ["super_admin", "org_admin", "admin"],
        "order": 17,
        "lessons": [
            {
                "slug": "mktg-website-leads",
                "title": "Website Lead Capture & Routing",
                "description": "How the website demo form captures leads and routes them into the platform.",
                "icon": "globe",
                "duration": "5 min",
                "order": 1,
                "video_url": "",
                "content": "## Website Lead Capture & Routing\n\nEvery form submission on imonsocial.com creates a lead, fires an email to sales@imonsocial.com, and routes to a shared inbox for immediate follow-up.\n\n### The Lead Flow\n1. Prospect fills out form on imonsocial.com\n2. Lead saved to DB (`demo_requests` collection)\n3. Email sent to `sales@imonsocial.com` with thread link\n4. Routes to the designated shared inbox (if configured)\n5. Assigned reps get push + SMS notification\n6. VA automatically handles the first response",
                "steps": [
                    "Configure the demo inbox: Hub → Set Up → Shared Inboxes → Edit → toggle 'Receive Website Leads' ON",
                    "Assign your sales team to this inbox so they get notified",
                    "Add a VA Profile to the inbox for automatic first response",
                    "Test: submit a test form at imonsocial.com → confirm email + inbox conversation appear",
                    "View all leads: Hub → Account Management → Hot Leads (engagement intel) — note: actual demo requests are in the Inbox",
                    "Response time goal: < 5 minutes during business hours",
                ],
            },
            {
                "slug": "mktg-social-proof",
                "title": "Collecting & Using Social Proof",
                "description": "How to collect client testimonials and use them in marketing.",
                "icon": "star",
                "duration": "4 min",
                "order": 2,
                "video_url": "",
                "content": "## Collecting & Using Social Proof\n\nTestimonials, results, and case studies are your best marketing assets. Every happy client is a story waiting to be told.",
                "steps": [
                    "Identify happy clients: Hub → Account Health → filter by high health score + 3+ months active",
                    "Ask at the right moment: right after a win ('You just closed your 10th lead this month through Jessi — congrats! Could we feature your results?')",
                    "Collect: video testimonial (best), written quote with photo, or results screenshot",
                    "Questions to ask: 'What was your biggest challenge before? What's changed? What would you tell someone considering this?'",
                    "Use testimonials on: imonsocial.com homepage, demo presentations, LinkedIn, email campaigns",
                    "Case study format: Dealership + reps + challenge + result (% increase in contact rate, sales closed) = 1-page PDF",
                ],
            },
            {
                "slug": "mktg-content-strategy",
                "title": "Content Strategy",
                "description": "What to post, when to post it, and which platforms to focus on.",
                "icon": "create",
                "duration": "5 min",
                "order": 3,
                "video_url": "",
                "content": "## Content Strategy\n\n### Who We're Talking To\n- Automotive sales managers and GMs\n- Sales professionals who handle their own follow-up\n- Business owners in local service industries\n\n### Platform Priority\n1. **LinkedIn** — decision makers, B2B, highest ROI for B2B sales\n2. **Facebook Groups** — dealer groups, local business communities\n3. **YouTube** — longer-form demos and tutorials\n4. **Email Newsletter** — best ROI, own your audience\n\n### Content Pillars (What to Post)\n- **Results** — lead response time stats, client wins\n- **Education** — tips for sales follow-up, relationship selling\n- **Behind the Scenes** — how Jessi works, feature reveals\n- **Social Proof** — client testimonials, before/after",
                "steps": [
                    "Post 3× per week minimum across LinkedIn and Facebook",
                    "Content calendar: Mon = Result/Stat, Wed = Educational tip, Fri = Client story or BTS",
                    "Every piece of content should link back to a demo booking or imonsocial.com",
                    "Repurpose: one long blog post → 5 short LinkedIn posts → 1 email → 2 short video clips",
                    "Track: which content drives demo requests? Check source='social' in the demo requests dashboard",
                ],
            },
            {
                "slug": "mktg-email",
                "title": "Email Marketing & Lead Nurturing",
                "description": "Email sequences for new leads, inactive prospects, and current clients.",
                "icon": "mail",
                "duration": "5 min",
                "order": 4,
                "video_url": "",
                "content": "## Email Marketing & Lead Nurturing\n\n### Email Sequences to Build\n1. **Demo Request Confirmation** — fires immediately after form submission\n2. **Post-Demo Follow-Up** — 5-email sequence over 14 days\n3. **Onboarding Welcome** — fires when a new client is created\n4. **Monthly Newsletter** — educational content + platform updates\n5. **Re-engagement** — for prospects who went cold 60+ days ago",
                "steps": [
                    "All transactional emails use Resend + templates in the platform",
                    "Demo request confirmation is already automated — verify it fires at sales@imonsocial.com",
                    "Post-demo sequence: build in a campaign in I'm On Social (use your own product!)",
                    "Newsletter: send on the 1st of each month — highlight one new feature, one client win, one tip",
                    "Subject line formula: [Benefit] + [Specificity] = 'How [Dealership] Contacted 87% of Their Leads in Under 5 Minutes'",
                    "Track open rates in the Email Analytics section",
                ],
            },
            {
                "slug": "mktg-partner-co-marketing",
                "title": "Partner & Reseller Co-Marketing",
                "description": "How to co-market with partners to expand reach without extra ad spend.",
                "icon": "business",
                "duration": "4 min",
                "order": 5,
                "video_url": "",
                "content": "## Partner & Reseller Co-Marketing\n\nPartners are your best distribution channel. A reseller with 50 dealer relationships is worth more than $50K in ads.",
                "steps": [
                    "Identify potential partners: consultants, 20 Group facilitators, dealer trainers, automotive vendors",
                    "Partner pitch: 'You already have the relationships — we pay you 20-40% of every account you bring on, monthly, for life. There's nothing to sell — just introduce us.'",
                    "Onboard partners: Hub → Account Management → Partner Portal → create agreement",
                    "Co-marketing: offer to present at their next conference, training, or 20 Group meeting",
                    "Create partner-specific landing pages (imonsocial.com/partner/[name]) with their branding",
                    "Monthly partner check-in: are they actively referring? Do they need updated collateral?",
                ],
            },
            {
                "slug": "mktg-analytics",
                "title": "Marketing Analytics & Attribution",
                "description": "How to track what's working — UTM params, lead sources, conversion rates.",
                "icon": "analytics",
                "duration": "4 min",
                "order": 6,
                "video_url": "",
                "content": "## Marketing Analytics & Attribution\n\nKnow where your leads come from so you can double down on what works.\n\n### UTM Parameters\nAdd UTM parameters to every link you share:\n- `utm_source=linkedin` / `utm_source=email` / `utm_source=partner_name`\n- `utm_medium=social` / `utm_medium=email` / `utm_medium=referral`\n- `utm_campaign=q1_outreach` / `utm_campaign=demo_webinar`\n\nExample: `imonsocial.com?utm_source=linkedin&utm_medium=social&utm_campaign=jan_push`",
                "steps": [
                    "Add utm_source and utm_medium to every link you share externally",
                    "View lead attribution: Hub → Account Management → Lead Attribution",
                    "Key metrics to track: demo requests by source, demo-to-close rate by source, cost per demo",
                    "Monthly review: which source drove the most demos last month? Double budget there.",
                    "Partner attribution: partners get a ref code (e.g. ?ref=PARTNER_JohnSmith) — all leads tracked to them",
                    "Review the Hot Leads page weekly: understanding where leads come from = better ad targeting",
                ],
            },
        ],
    },

]


async def run():
    from motor.motor_asyncio import AsyncIOMotorClient
    MONGO_URL = os.environ.get("MONGO_URL")
    DB_NAME   = os.environ.get("DB_NAME", "imos_db")
    if not MONGO_URL:
        print("ERROR: MONGO_URL not set")
        return

    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]

    created_tracks  = 0
    created_lessons = 0
    skipped = 0

    for track_data in INTERNAL_TRACKS:
        existing = await db.training_tracks.find_one({"slug": track_data["slug"]})
        if existing:
            print(f"  SKIP  '{track_data['title']}' (already exists)")
            skipped += 1
            continue

        lessons = track_data.pop("lessons", [])
        track_data["created_at"] = __import__("datetime").datetime.utcnow()
        track_data["updated_at"] = __import__("datetime").datetime.utcnow()

        result = await db.training_tracks.insert_one(track_data)
        track_id = str(result.inserted_id)

        for lesson in lessons:
            lesson["track_id"]    = track_id
            lesson["created_at"]  = __import__("datetime").datetime.utcnow()
            lesson["updated_at"]  = __import__("datetime").datetime.utcnow()
            await db.training_lessons.insert_one(lesson)
            created_lessons += 1

        print(f"  ✅ Created '{track_data['title']}' with {len(lessons)} lessons")
        created_tracks += 1

    client.close()
    print(f"\nDone: {created_tracks} tracks created, {created_lessons} lessons created, {skipped} skipped")


if __name__ == "__main__":
    asyncio.run(run())
