/**
 * contactStyles.ts — All styles for the contact detail page.
 * Extracted from contact/[id].tsx to keep the main file focused on logic & JSX.
 */
import { StyleSheet } from 'react-native';

export const getS = (colors: any) => StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },

  // Header
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 12, paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerBtn: { padding: 4, minWidth: 50 },
  headerTitle: { fontSize: 18, fontWeight: '600', flex: 1, textAlign: 'center', color: colors.text },
  headerAction: { fontSize: 18, fontWeight: '600', color: '#C9A962' },
  scroll: { paddingBottom: 32 },

  // Hero section  - compact left-aligned
  heroSection: {
    paddingHorizontal: 16, paddingTop: 12, paddingBottom: 12,
  },
  heroRow: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 14,
  },
  heroAvatarContainer: { position: 'relative' },
  heroAvatar: { width: 68, height: 68, borderRadius: 18, borderWidth: 2, borderColor: '#C9A962', resizeMode: 'cover' as const },
  heroAvatarPlaceholder: {
    width: 68, height: 68, borderRadius: 18,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 2,
  },
  heroInitials: { fontSize: 24, fontWeight: '700', color: '#C9A962' },
  heroCameraBadge: {
    position: 'absolute', bottom: -2, right: -2,
    width: 24, height: 24, borderRadius: 12,
    backgroundColor: '#C9A962', alignItems: 'center', justifyContent: 'center',
    borderWidth: 2, borderColor: colors.border,
  },
  touchpointBadge: {
    position: 'absolute', top: -4, right: -4,
    backgroundColor: '#C9A962', borderRadius: 10,
    minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center',
    paddingHorizontal: 5, borderWidth: 2, borderColor: colors.border,
  },
  touchpointBadgeText: { fontSize: 12, fontWeight: '800', color: colors.text },
  heroInfo: { flex: 1, paddingTop: 2 },
  heroName: { fontSize: 21, fontWeight: '700', marginBottom: 4, color: colors.text },
  heroTagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 6 },
  heroTag: {
    flexDirection: 'row', alignItems: 'center', gap: 3,
    paddingVertical: 2, paddingHorizontal: 7,
    borderRadius: 10, borderWidth: 1, borderColor: colors.border,
    backgroundColor: colors.card,
  },
  heroTagText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
  heroTagMore: { fontSize: 12, fontWeight: '600', color: colors.textTertiary, alignSelf: 'center' },
  heroTagAdd: {
    width: 20, height: 20, borderRadius: 10,
    backgroundColor: '#007AFF20', borderWidth: 1, borderColor: '#007AFF40',
    alignItems: 'center', justifyContent: 'center',
    alignSelf: 'center',
  },
  heroHighlight: {
    flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 4,
  },
  heroHighlightText: { fontSize: 15, color: '#C9A962', fontWeight: '600' },
  heroMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  heroMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  heroMetaText: { fontSize: 14, color: colors.textTertiary },
  heroStatsLine: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap',
    marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.border,
    gap: 4,
  },
  heroStatChip: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
  heroStatVal: { fontSize: 15, fontWeight: '700', color: colors.text },
  heroStatLbl: { fontSize: 13, color: colors.textTertiary },
  heroStatDot: { fontSize: 13, color: colors.textTertiary, marginHorizontal: 1 },

  heroTagsStrip: { paddingHorizontal: 16, paddingTop: 6, paddingBottom: 4 },
  heroTagsStripHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  heroTagsStripTitle: { fontSize: 13, fontWeight: '700', color: '#FF9500', textTransform: 'uppercase', letterSpacing: 0.5, flex: 1 },
  heroTagsStripAdd: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#007AFF15', alignItems: 'center', justifyContent: 'center' },
  heroTagChip: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, borderWidth: 1 },
  heroTagChipText: { fontSize: 14, fontWeight: '600', maxWidth: 120, color: colors.text },
  heroTagsEmpty: { fontSize: 14, color: colors.textTertiary, fontStyle: 'italic', paddingBottom: 4 },

  heroCampaignsStrip: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 4, borderTopWidth: 1, borderTopColor: colors.border },
  heroCampaignsHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  heroCampaignsTitle: { fontSize: 13, fontWeight: '700', color: '#AF52DE', textTransform: 'uppercase', letterSpacing: 0.5, flex: 1 },
  heroCampaignsAdd: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#007AFF15', alignItems: 'center', justifyContent: 'center' },
  heroCampaignChip: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, borderWidth: 1 },
  heroCampaignChipText: { fontSize: 14, fontWeight: '600', maxWidth: 120, color: colors.text },
  heroCampaignStep: { fontSize: 12, fontWeight: '700', color: colors.text, paddingHorizontal: 4, paddingVertical: 1, borderRadius: 6 },
  heroCampaignDate: { fontSize: 12, fontWeight: '700', color: colors.text, paddingHorizontal: 5, paddingVertical: 1, borderRadius: 6 },

  tabBar: { flexDirection: 'row', marginHorizontal: 16, marginTop: 4, borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 3, gap: 4 },
  tabBtn: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 11 },
  tabBtnActive: { backgroundColor: '#C9A962' },
  tabBtnText: { fontSize: 17, fontWeight: '700', color: '#888' },
  tabBtnTextActive: { color: '#000' },

  pinnedNote: { flexDirection: 'row', gap: 8, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: colors.card, borderRadius: 10, borderLeftWidth: 3, borderLeftColor: '#C9A962' },
  pinnedNoteText: { flex: 1, fontSize: 16, color: colors.textSecondary, lineHeight: 20 },

  taskBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginHorizontal: 16, marginBottom: 16, padding: 14, backgroundColor: '#FF950012', borderRadius: 12, borderLeftWidth: 3, borderLeftColor: '#FF9500' },
  taskBannerIcon: { marginTop: 2 },
  taskBannerLabel: { fontSize: 13, fontWeight: '700', color: '#FF9500', textTransform: 'uppercase', letterSpacing: 0.5 },
  taskBannerTitle: { fontSize: 17, fontWeight: '600', color: colors.text, marginTop: 2 },
  taskBannerDesc: { fontSize: 15, color: colors.textSecondary, marginTop: 2, lineHeight: 18 },
  taskBannerClose: { padding: 4 },

  stickyBar: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: colors.bg, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: 8, paddingBottom: 12 },
  stickyBarInner: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12 },
  stickyBtn: { alignItems: 'center', gap: 4, paddingHorizontal: 8, minWidth: 50 },
  stickyBtnIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  stickyBtnLabel: { fontSize: 9, color: colors.textSecondary, fontWeight: '600', textAlign: 'center' },

  // Inline Composer
  composerContainer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: colors.bg, borderTopWidth: 1, borderTopColor: colors.border, paddingHorizontal: 12, paddingTop: 8, paddingBottom: 16 },
  composerModeRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  composerModeBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 5, borderRadius: 16, borderWidth: 1 },
  composerModeBtnActive: {},
  composerModeBtnText: { fontSize: 14, fontWeight: '600', color: colors.text },
  composerCallBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#32ADE615', alignItems: 'center', justifyContent: 'center' },
  composerBox: { borderRadius: 16, borderWidth: 1, overflow: 'hidden' },
  composerInput: { fontSize: 18, color: colors.text, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 10, textAlignVertical: 'top' },
  composerToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, paddingVertical: 6, borderTopWidth: 1 },
  composerTools: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  composerToolBtn: { width: 38, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  composerSendBtn: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  aiSuggestionBubble: { backgroundColor: `${colors.success}08`, borderRadius: 14, padding: 12, marginBottom: 8, borderWidth: 1.5, borderColor: `${colors.success}40` },
  aiSuggestionHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  aiSuggestionLabel: { fontSize: 14, fontWeight: '700', color: '#34C759', flex: 1, textTransform: 'uppercase', letterSpacing: 0.5 },
  aiSuggestionText: { fontSize: 16, color: colors.text, lineHeight: 20, marginBottom: 10 },
  aiSuggestionActions: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' },
  aiActionBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  aiActionBtnSend: { backgroundColor: '#34C759', borderColor: '#34C759' },
  aiActionBtnText: { fontSize: 15, fontWeight: '600', color: '#007AFF' },

  // Toolbar Modals
  toolbarModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-start', paddingTop: 20 },
  toolbarModal: { backgroundColor: colors.surface, borderRadius: 20, marginHorizontal: 10, flex: 1, marginBottom: 20 },
  toolbarModalHeader: { paddingTop: 12, paddingBottom: 16, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: colors.border },
  toolbarModalHandle: { width: 36, height: 5, backgroundColor: colors.borderLight, borderRadius: 3, alignSelf: 'center', marginBottom: 16 },
  toolbarModalTitle: { fontSize: 21, fontWeight: '700', color: colors.text, textAlign: 'center' },
  toolbarTemplatesList: { flex: 1 },
  toolbarTemplatesListContent: { padding: 16, paddingBottom: 8 },
  toolbarModalFooter: { padding: 16, paddingBottom: 32, borderTopWidth: 1, borderTopColor: colors.border },
  toolbarModalCloseBtn: { backgroundColor: colors.card, borderRadius: 12, padding: 16, alignItems: 'center' },
  toolbarModalCloseBtnText: { fontSize: 18, fontWeight: '600', color: '#FF3B30' },
  toolbarTemplateItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderRadius: 12, padding: 14, marginBottom: 10 },
  toolbarTemplateIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#007AFF20', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  toolbarTemplateContent: { flex: 1 },
  toolbarTemplateName: { fontSize: 18, fontWeight: '600', color: colors.text },
  toolbarTemplatePreview: { fontSize: 15, color: colors.textSecondary, marginTop: 2 },
  toolbarEmptyTemplates: { alignItems: 'center', paddingVertical: 40 },
  toolbarEmptyTemplatesText: { fontSize: 18, color: colors.textSecondary, marginTop: 12 },
  toolbarEmptyReviews: { alignItems: 'center', paddingVertical: 32 },
  toolbarEmptyReviewsText: { fontSize: 18, color: colors.textSecondary, marginTop: 12, marginBottom: 20 },
  toolbarSetupBtn: { backgroundColor: '#007AFF', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 20 },
  toolbarSetupBtnText: { fontSize: 18, fontWeight: '600', color: '#FFF' },

  cardModalContent: { padding: 20 },
  cardPreview: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 16, padding: 24, marginBottom: 20 },
  cardPreviewTitle: { fontSize: 19, fontWeight: '600', color: colors.text, marginTop: 12 },
  cardPreviewDesc: { fontSize: 16, color: colors.textSecondary, textAlign: 'center', marginTop: 8, lineHeight: 20 },
  shareOptionsContainer: { marginTop: 20, gap: 12 },
  shareOptionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderRadius: 14, padding: 16 },
  shareOptionIcon: { width: 50, height: 50, borderRadius: 12, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  shareOptionContent: { flex: 1 },
  shareOptionTitle: { fontSize: 18, fontWeight: '600', color: colors.text, marginBottom: 4 },
  shareOptionDesc: { fontSize: 15, color: colors.textSecondary, lineHeight: 18 },
  landingPageOptions: { marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: colors.border },
  landingPageOptionsHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16, gap: 12 },
  landingPageOptionsTitle: { fontSize: 18, fontWeight: '600', color: colors.text },
  campaignPickerLabel: { fontSize: 17, fontWeight: '500', color: colors.text, marginBottom: 12 },
  campaignScroller: { maxHeight: 50, marginBottom: 20 },
  campaignScrollerContent: { paddingRight: 20 },
  campaignChip: { paddingHorizontal: 16, paddingVertical: 10, backgroundColor: colors.card, borderRadius: 20, marginRight: 10, borderWidth: 2, borderColor: 'transparent' },
  campaignChipSelected: { backgroundColor: '#007AFF20', borderColor: '#007AFF' },
  campaignChipText: { fontSize: 16, color: colors.textSecondary, fontWeight: '500' },
  campaignChipTextSelected: { color: '#007AFF' },
  noCampaigns: { alignItems: 'center', paddingVertical: 20 },
  noCampaignsText: { fontSize: 17, color: colors.textSecondary },
  noCampaignsSubtext: { fontSize: 15, color: colors.textTertiary, marginTop: 4 },
  sendCardButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#007AFF', borderRadius: 12, padding: 16, gap: 8 },
  sendCardButtonText: { fontSize: 18, fontWeight: '600', color: '#FFF' },

  actionSheetOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  actionSheetContainer: { paddingHorizontal: 8, paddingBottom: 8 },
  actionSheetGroup: { backgroundColor: colors.card, borderRadius: 14, overflow: 'hidden', marginBottom: 8 },
  actionSheetButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 18, gap: 10 },
  actionSheetButtonText: { fontSize: 21, color: '#007AFF', fontWeight: '400' },
  actionSheetDivider: { height: 1, backgroundColor: colors.border },
  actionSheetCancel: { backgroundColor: colors.card, borderRadius: 14, paddingVertical: 18, alignItems: 'center' },
  actionSheetCancelText: { fontSize: 21, fontWeight: '600', color: '#007AFF' },

  sendPickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  sendPickerSheet: { backgroundColor: colors.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingTop: 12, paddingBottom: 32, paddingHorizontal: 16 },
  sendPickerHandle: { width: 36, height: 4, backgroundColor: colors.borderLight, borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  sendPickerTitle: { fontSize: 19, fontWeight: '700', marginBottom: 16, color: colors.text },
  sendPickerItem: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, borderBottomWidth: 1 },
  sendPickerIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  sendPickerLabel: { fontSize: 18, fontWeight: '600', color: colors.text },
  sendPickerSub: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },

  feedDateHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10, marginTop: 4 },
  feedDateLine: { flex: 1, height: 1, backgroundColor: colors.border },
  feedDateText: { fontSize: 13, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.8 },
  feedDateCount: { fontSize: 12, fontWeight: '700', color: colors.textSecondary, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, backgroundColor: colors.surface },

  progressSection: { marginHorizontal: 16, marginBottom: 12, borderRadius: 14, padding: 12 },
  progressHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  progressLabel: { fontSize: 14, fontWeight: '700', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5 },
  progressBarBg: { flex: 1, height: 4, backgroundColor: colors.surface, borderRadius: 2, overflow: 'hidden' },
  progressBarFill: { height: 4, backgroundColor: '#C9A962', borderRadius: 2 },
  progressRow: { flexDirection: 'row', gap: 8 },
  progressItem: { alignItems: 'center', gap: 4, minWidth: 56 },
  progressItemDone: {},
  progressIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border },
  progressText: { fontSize: 9, fontWeight: '600', color: colors.textSecondary, textAlign: 'center' },

  section: { marginHorizontal: 16, marginBottom: 16 },
  sectionHeader: { fontSize: 15, fontWeight: '600', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 10 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  sectionHeaderCount: { fontSize: 14, color: colors.textTertiary },

  tagsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagPill: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 16, paddingVertical: 6, paddingHorizontal: 12, borderWidth: 1, borderColor: colors.border },
  tagPillText: { fontSize: 15, fontWeight: '500', color: colors.text },
  addTagChip: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#007AFF15', borderRadius: 16, paddingVertical: 6, paddingHorizontal: 12, borderWidth: 1, borderColor: '#007AFF30', borderStyle: 'dashed' },
  addTagChipText: { fontSize: 15, fontWeight: '600', color: '#007AFF' },

  emptyFeed: { alignItems: 'center', paddingVertical: 32 },
  emptyFeedText: { fontSize: 18, color: colors.textSecondary, marginTop: 8 },
  emptyFeedSub: { fontSize: 16, color: colors.textTertiary, marginTop: 4, textAlign: 'center' },
  feedTimeline: { gap: 0 },
  feedItem: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 10, position: 'relative' },
  feedItemInbound: { backgroundColor: '#30D15808', borderRadius: 12, marginVertical: 2, paddingHorizontal: 4 },
  feedLine: { position: 'absolute', left: 17, top: 42, bottom: -10, width: 2 },
  feedIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  feedContent: { flex: 1 },
  feedTitle: { fontSize: 16, fontWeight: '600', color: colors.text, marginBottom: 2 },
  feedDesc: { fontSize: 16, color: colors.textSecondary, marginBottom: 4 },
  feedExpandedPreview: { marginTop: 8, marginBottom: 4, gap: 6 },
  feedChannelBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  feedChannelText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5 },
  feedSubject: { fontSize: 16, fontWeight: '600', color: colors.textSecondary },
  feedMessageBubble: { borderRadius: 10, padding: 12, borderWidth: 1, borderColor: colors.border },
  feedMessageBubbleInbound: { backgroundColor: '#30D15812', borderColor: '#30D15830' },
  feedMessageText: { fontSize: 16, lineHeight: 20, color: colors.text },
  feedViewLink: { flexDirection: 'row', alignItems: 'center', gap: 4, alignSelf: 'flex-start', paddingVertical: 4 },
  feedViewLinkText: { fontSize: 15, color: '#007AFF', fontWeight: '500' },
  feedTime: { fontSize: 15, color: colors.textTertiary },
  feedPhotoIndicator: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 4 },
  feedPhotoText: { fontSize: 14, color: '#30D158', fontWeight: '500' },
  inboundBadge: { backgroundColor: '#30D15820', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  inboundBadgeText: { fontSize: 9, fontWeight: '700', color: '#30D158', letterSpacing: 0.5 },
  customerBadge: { backgroundColor: '#FFD60A20', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  customerBadgeText: { fontSize: 9, fontWeight: '700', color: '#FFD60A', letterSpacing: 0.5 },
  feedActionRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  logReplyBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#30D15815', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: '#30D15830' },
  logReplyBtnText: { fontSize: 15, fontWeight: '600', color: '#30D158' },
  feedSearchRowCompact: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  feedSearchInputCompact: { flex: 1, fontSize: 15, padding: 0, color: colors.text },
  logReplyBubble: { backgroundColor: '#1A2E1A', borderRadius: 20, padding: 16, marginBottom: 14, borderWidth: 1.5, borderColor: '#30D15850', position: 'relative' },
  bubbleTail: { position: 'absolute', top: -8, left: 24, width: 16, height: 16, backgroundColor: '#1A2E1A', borderTopWidth: 1.5, borderLeftWidth: 1.5, borderColor: '#30D15850', transform: [{ rotate: '45deg' }] },
  bubbleHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  bubbleHeaderText: { fontSize: 16, fontWeight: '700', color: '#30D158', flex: 1 },
  bubbleClose: { padding: 2 },
  bubbleInputWrap: { backgroundColor: '#0D1A0D', borderRadius: 16, borderWidth: 1, borderColor: '#30D15830', marginBottom: 10 },
  bubbleInput: { fontSize: 17, color: colors.text, padding: 14, minHeight: 80, textAlignVertical: 'top', lineHeight: 22 },
  bubblePhotoPreview: { position: 'relative', width: 80, height: 80, borderRadius: 12, overflow: 'hidden', marginBottom: 10 },
  bubblePhotoThumb: { width: 80, height: 80, borderRadius: 12 },
  bubblePhotoRemove: { position: 'absolute', top: -2, right: -2 },
  bubbleFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  bubblePhotoBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#0D1A0D', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#30D15830' },
  bubbleSaveBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#30D158', borderRadius: 24, paddingVertical: 12, paddingHorizontal: 20 },
  bubbleSaveText: { fontSize: 17, fontWeight: '800', color: colors.text },
  actionBadge: { backgroundColor: '#FF9500', borderRadius: 10, minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  actionBadgeText: { fontSize: 13, fontWeight: '800', color: colors.text },
  suggestedCard: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 14, marginBottom: 8, borderWidth: 1 },
  suggestedIcon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  suggestedTitle: { fontSize: 17, fontWeight: '700', marginBottom: 2, color: colors.text },
  suggestedDesc: { fontSize: 16, color: colors.textSecondary },
  suggestedMsgPreview: { marginTop: 6, borderRadius: 8, padding: 8, borderWidth: 1 },
  suggestedMsgText: { fontSize: 14, fontStyle: 'italic', lineHeight: 16, color: colors.textSecondary },
  suggestedArrow: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  showMoreBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 12, paddingVertical: 10, borderRadius: 10, borderWidth: 1 },
  showMoreText: { fontSize: 16, fontWeight: '600', color: '#007AFF' },

  galleryRoot: { flex: 1, backgroundColor: '#000', maxWidth: 480, width: '100%', alignSelf: 'center' as const },
  galleryTopBar: { flexDirection: 'row' as const, alignItems: 'center', justifyContent: 'space-between', paddingTop: 12, paddingHorizontal: 16, paddingBottom: 12, backgroundColor: '#000' },
  galleryCloseBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.12)', justifyContent: 'center', alignItems: 'center' },
  galleryTopTitle: { color: '#FFF', fontSize: 17, fontWeight: '600', letterSpacing: 0.3 },
  galleryUploadBtn: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  viewerBottomBar: { flexDirection: 'row' as const, alignItems: 'center', paddingHorizontal: 20, paddingBottom: 34, paddingTop: 12, backgroundColor: '#000', gap: 12 },
  viewerLabel: { color: '#FFF', fontSize: 17, fontWeight: '600' },
  viewerDate: { color: 'rgba(255,255,255,0.4)', fontSize: 14, marginTop: 2 },
  viewerActionBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.12)', justifyContent: 'center', alignItems: 'center' },
  galleryGrid: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 1 },
  galleryTile: { width: `${(100 / 3) - 0.1}%` as any, aspectRatio: 1, overflow: 'hidden' as const, position: 'relative' as const, backgroundColor: 'rgba(255,255,255,0.04)' },
  galleryTileImg: { width: '100%', height: '100%' },
  profileBadge: { position: 'absolute' as const, top: 6, left: 6, width: 24, height: 24, borderRadius: 12, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  setProfileOverlay: { position: 'absolute' as const, bottom: 6, right: 6, width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'center', alignItems: 'center' },

  vnRecordBtn: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  vnRecordText: { fontSize: 17, fontWeight: '600', color: colors.textSecondary },
  vnRecording: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 12, backgroundColor: '#2E1A1A', borderWidth: 1, borderColor: '#FF3B3030' },
  vnRecordingDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#FF3B30' },
  vnRecordingTime: { fontSize: 21, fontWeight: '700', color: '#FF3B30', fontVariant: ['tabular-nums'] as any },
  vnRecordingLimit: { fontSize: 16, color: colors.textTertiary },
  vnStopBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, marginLeft: 'auto', paddingVertical: 6, paddingHorizontal: 14, borderRadius: 8, backgroundColor: '#FF3B30' },
  vnStopText: { fontSize: 16, fontWeight: '600', color: colors.text },
  vnCard: { borderRadius: 12, padding: 12, marginBottom: 8, borderWidth: 1 },
  vnCardHeader: { flexDirection: 'row', alignItems: 'center' },
  vnPlayBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#34C75920', justifyContent: 'center', alignItems: 'center' },
  vnPlayBtnActive: { backgroundColor: '#34C759' },
  vnCardDate: { fontSize: 16, fontWeight: '600', color: colors.text },
  vnCardDuration: { fontSize: 15, color: colors.textTertiary },
  vnTranscript: { fontSize: 16, color: colors.textSecondary, lineHeight: 20, marginTop: 8 },

  intelBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: '#C9A96230' },
  intelBtnLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  intelIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#C9A96220', justifyContent: 'center', alignItems: 'center' },
  intelBtnTitle: { fontSize: 17, fontWeight: '700', color: '#C9A962' },
  intelBtnSub: { fontSize: 14, color: colors.textTertiary, marginTop: 1 },
  intelUpdateBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4, backgroundColor: '#C9A96215', borderRadius: 8, borderWidth: 1, borderColor: '#C9A96230' },
  intelUpdateBtnText: { fontSize: 13, fontWeight: '700', color: '#C9A962' },
  intelCard: { marginTop: 8, padding: 14, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  intelLoading: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 20, justifyContent: 'center' },
  intelLoadingText: { fontSize: 16, color: '#C9A962', fontStyle: 'italic' },
  intelSummary: { fontSize: 15.5, color: colors.textSecondary, lineHeight: 20 },
  intelMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.border },
  intelMetaText: { fontSize: 13, color: colors.textTertiary, flex: 1 },
  intelRefresh: { flexDirection: 'row', alignItems: 'center', gap: 4, padding: 4 },
  intelRefreshText: { fontSize: 14, fontWeight: '600', color: '#007AFF' },
  intelEmpty: { fontSize: 16, color: colors.textTertiary, textAlign: 'center', paddingVertical: 16 },

  conversationLink: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 16, marginBottom: 16, backgroundColor: colors.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: colors.border },
  conversationLinkTitle: { fontSize: 17, fontWeight: '600', color: colors.text },
  conversationLinkSub: { fontSize: 15, color: colors.textSecondary, marginTop: 1 },

  inputGroup: { marginBottom: 12 },
  inputLabel: { fontSize: 14, fontWeight: '500', color: colors.textSecondary, marginBottom: 4, marginLeft: 2 },
  input: { backgroundColor: colors.card, borderRadius: 10, padding: 14, fontSize: 18, color: colors.text, borderWidth: 1, borderColor: colors.border },

  dateRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderRadius: 10, padding: 12, marginBottom: 8, borderWidth: 1, borderColor: colors.border },
  dateRowIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  dateRowLabel: { fontSize: 14, color: colors.textSecondary, marginBottom: 1 },
  dateRowValue: { fontSize: 17, fontWeight: '600', color: colors.text },

  addBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#007AFF15', borderRadius: 10, padding: 12, marginTop: 4, borderWidth: 1, borderColor: '#007AFF30', borderStyle: 'dashed' },
  addBtnText: { fontSize: 17, fontWeight: '600', color: '#007AFF' },

  deleteBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginHorizontal: 16, marginTop: 8, paddingVertical: 14, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: '#FF3B3040' },
  deleteBtnText: { fontSize: 18, fontWeight: '600', color: '#FF3B30' },

  viewText: { fontSize: 17, color: colors.text, lineHeight: 22 },
  viewRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.border },
  viewRowLabel: { fontSize: 16, color: colors.textSecondary, flex: 1 },
  viewRowValue: { fontSize: 16, fontWeight: '600', color: colors.text },

  referralItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.border },
  referralAvatar: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
  referralAvatarText: { fontSize: 14, fontWeight: '600', color: colors.text },
  referralName: { flex: 1, fontSize: 16, fontWeight: '500', color: colors.text },

  campaignCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderRadius: 10, padding: 12, marginBottom: 8, borderWidth: 1, borderColor: colors.border },
  campaignName: { fontSize: 17, fontWeight: '600', color: colors.text },
  campaignSub: { fontSize: 15, color: colors.textSecondary, marginTop: 1 },

  modalContainer: { flex: 1, backgroundColor: colors.bg },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
  modalCancel: { fontSize: 18, color: '#007AFF' },
  modalTitle: { fontSize: 18, fontWeight: '600', color: colors.text },
  modalAction: { fontSize: 18, color: '#007AFF' },
  modalSearch: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderRadius: 10, margin: 16, paddingHorizontal: 12, gap: 8 },
  modalSearchInput: { flex: 1, padding: 12, fontSize: 18, color: colors.text },
  pickerItem: { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1, borderBottomColor: colors.border, gap: 10 },
  pickerItemText: { fontSize: 18, fontWeight: '500', color: colors.text },
  pickerAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  pickerAvatarText: { fontSize: 17, fontWeight: '600', color: colors.text },
  pickerName: { fontSize: 18, fontWeight: '500', color: colors.text },
  pickerSub: { fontSize: 16, color: colors.textSecondary, marginTop: 1 },
  emptyPicker: { padding: 32, alignItems: 'center' },
  emptyPickerText: { fontSize: 18, color: colors.textSecondary },

  dateOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  dateModal: { backgroundColor: colors.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 20 },
  dateModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
  dateConfirmBtn: { backgroundColor: '#007AFF', borderRadius: 12, padding: 16, alignItems: 'center' },

  webPickerLabel: { fontSize: 14, fontWeight: '600', color: colors.textSecondary, marginBottom: 8, textTransform: 'uppercase' },
  webPickerScroll: { maxHeight: 200, width: '100%', backgroundColor: colors.surface, borderRadius: 8 },
  webPickerItem: { paddingVertical: 10, paddingHorizontal: 12, alignItems: 'center' },
  webPickerItemSel: { backgroundColor: '#007AFF', borderRadius: 6, marginHorizontal: 4 },
  webPickerText: { fontSize: 18, color: colors.textSecondary },
  webPickerTextSel: { color: colors.text, fontWeight: '600' },

  labelOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-start', paddingTop: 150 },
  labelModal: { backgroundColor: colors.card, borderRadius: 16, marginHorizontal: 20, padding: 24 },
  labelTitle: { fontSize: 21, fontWeight: '700', color: colors.text, textAlign: 'center', marginBottom: 8 },
  labelSub: { fontSize: 17, color: '#007AFF', textAlign: 'center', marginBottom: 20, fontWeight: '600' },
  labelInput: { backgroundColor: colors.surface, borderRadius: 12, padding: 16, fontSize: 18, color: colors.text, marginBottom: 24 },
  labelBtn: { flex: 1, borderRadius: 12, padding: 16, alignItems: 'center' },
});
