import type { PreviewConfig } from './_preview';

export const PAGES: Record<string, PreviewConfig> = {
  inbox: {
    title: 'Inbox',
    subtitle: 'Messaging Hub',
    description: 'Your unified messaging command center. Every SMS and email conversation in one place, with AI-powered response suggestions.',
    icon: 'chatbubble',
    iconColor: '#007AFF',
    bullets: [
      'Unified SMS and email conversations in a single inbox',
      'AI-powered response suggestions from Jessi',
      'Thread-based conversations with full history',
      'Search across all messages instantly',
      'Quick reply templates for common responses',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'person', label: 'Sarah Johnson', sub: 'Thanks for the birthday card!', badge: '2', badgeColor: '#007AFF' },
        { icon: 'person', label: 'Mike Davis', sub: 'When can I come pick it up?', badge: '1', badgeColor: '#007AFF' },
        { icon: 'person', label: 'Lisa Chen', sub: 'Great experience, thank you!', badge: '', badgeColor: '#34C759' },
        { icon: 'person', label: 'Robert Wilson', sub: 'Is the warranty still active?', badge: '3', badgeColor: '#FF3B30' },
        { icon: 'person', label: 'Emma Thompson', sub: 'Love the new model!', badge: '', badgeColor: '#34C759' },
      ],
    },
  },
  contacts: {
    title: 'Contacts',
    subtitle: 'Relationship Management',
    description: 'Your customer database with smart tagging, automated campaigns, and a complete interaction history for every contact.',
    icon: 'people',
    iconColor: '#5856D6',
    bullets: [
      'Full contact profiles with photos, notes, and tags',
      'Automatic campaign enrollment on tag changes',
      'Birthday, anniversary, and sold-date tracking',
      'CSV import/export for bulk operations',
      'Smart search and filter by any field',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'person', label: 'Sarah Johnson', sub: 'Birthday: Mar 15 · Sold: Jan 2026', badge: 'VIP', badgeColor: '#C9A962' },
        { icon: 'person', label: 'Mike Davis', sub: 'Anniversary: Feb 20 · 3 tags', badge: 'Sold', badgeColor: '#34C759' },
        { icon: 'person', label: 'Lisa Chen', sub: 'Added 2 days ago · New lead', badge: 'New', badgeColor: '#007AFF' },
        { icon: 'person', label: 'Robert Wilson', sub: 'Referred by Sarah · Active campaign', badge: 'Active', badgeColor: '#FF9500' },
        { icon: 'person', label: 'Emma Thompson', sub: 'Last contact: yesterday', badge: '', badgeColor: '' },
      ],
    },
  },
  dialer: {
    title: 'Dialer',
    subtitle: 'Phone System',
    description: 'Call customers directly from the app. Every call is logged, timestamped, and attached to the right contact.',
    icon: 'keypad',
    iconColor: '#34C759',
    bullets: [
      'One-tap dialing from any contact profile',
      'Automatic call logging with timestamps',
      'Call history with duration and outcomes',
      'Voicemail detection and notes',
      'Click-to-call from any phone number in the app',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '47', label: 'Calls Today', color: '#34C759' },
        { value: '3:24', label: 'Avg Duration', color: '#007AFF' },
        { value: '89%', label: 'Answer Rate', color: '#C9A962' },
        { value: '12', label: 'Callbacks Due', color: '#FF9500' },
      ],
    },
  },
  team: {
    title: 'Team Chat',
    subtitle: 'Internal Communication',
    description: 'Real-time team messaging. Share updates, celebrate wins, and coordinate without leaving the app.',
    icon: 'chatbubbles',
    iconColor: '#FF9500',
    bullets: [
      'Real-time team messaging and channels',
      'Share contacts, deals, and congrats cards',
      'Pin important announcements',
      'React and reply to messages',
      'File sharing and media support',
    ],
    mockup: {
      type: 'chat',
      messages: [
        { from: 'them', text: 'Just closed the Johnson deal! 🎉', time: '9:42 AM' },
        { from: 'me', text: 'Amazing work! Congrats card sent!', time: '9:43 AM' },
        { from: 'them', text: 'They loved it. Already shared on Facebook', time: '9:44 AM' },
        { from: 'me', text: 'That\'s what we like to see. Campaign auto-enrolled.', time: '9:45 AM' },
        { from: 'them', text: 'This system is incredible', time: '9:45 AM' },
      ],
    },
  },
  more: {
    title: 'More',
    subtitle: 'Navigation Hub',
    description: 'Your command center for everything in iMOs. Access all tools, settings, and features from one organized menu.',
    icon: 'menu',
    iconColor: '#8E8E93',
    bullets: [
      'Organized access to all app features',
      'Quick links to communication tools',
      'Campaign management shortcuts',
      'Settings and profile access',
      'Admin tools for managers',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'chatbubbles', label: 'Communication', sub: 'Inbox, Broadcast, Team Chat', badge: '', badgeColor: '' },
        { icon: 'rocket', label: 'Campaigns', sub: 'SMS, Email, Date Triggers', badge: '', badgeColor: '' },
        { icon: 'trophy', label: 'Performance', sub: 'Leaderboard, Analytics, Reports', badge: '', badgeColor: '' },
        { icon: 'settings', label: 'Settings', sub: 'Profile, Security, Integrations', badge: '', badgeColor: '' },
        { icon: 'shield', label: 'Admin', sub: 'Users, Stores, Organizations', badge: '', badgeColor: '' },
      ],
    },
  },
  broadcast: {
    title: 'Broadcast',
    subtitle: 'Team Communication',
    description: 'Send announcements, updates, and motivation to your entire team with one tap. Keep everyone aligned.',
    icon: 'megaphone',
    iconColor: '#FF9500',
    bullets: [
      'One-tap messaging to your entire team',
      'Target specific roles or stores',
      'Schedule broadcasts for optimal timing',
      'Read receipts and engagement tracking',
      'Rich text with images and links',
    ],
    mockup: {
      type: 'chat',
      messages: [
        { from: 'me', text: 'Team! New holiday campaign templates are live. Check them out in Campaigns.', time: '8:00 AM' },
        { from: 'them', text: 'Manager: Got it! Already setting up Thanksgiving.', time: '8:12 AM' },
        { from: 'them', text: 'Sales Rep: These look great, thanks!', time: '8:15 AM' },
      ],
    },
  },
  campaigns: {
    title: 'SMS Campaigns',
    subtitle: 'Automated Follow-ups',
    description: 'Build multi-step SMS campaigns that run automatically. Tag a contact, trigger a sequence, build a relationship.',
    icon: 'chatbubbles',
    iconColor: '#FF2D55',
    bullets: [
      'Multi-step SMS sequences triggered by tags',
      'Customizable delays between messages',
      'Template variables for personalization',
      'Enrollment tracking and analytics',
      'Pause, resume, and edit live campaigns',
    ],
    mockup: {
      type: 'cards',
      cards: [
        { icon: 'car-sport', title: 'Sold Follow-up', sub: '5 steps · 847 enrolled', color: '#34C759' },
        { icon: 'gift', title: 'Birthday Drip', sub: '3 steps · 1.2k enrolled', color: '#FF9500' },
        { icon: 'heart', title: 'Anniversary', sub: '4 steps · 623 enrolled', color: '#FF2D55' },
        { icon: 'snow', title: 'Holiday Greetings', sub: '2 steps · 2.1k enrolled', color: '#007AFF' },
      ],
    },
  },
  'campaigns-email': {
    title: 'Email Campaigns',
    subtitle: 'Automated Email',
    description: 'Beautiful, automated email sequences. From welcome emails to annual check-ins — all running on autopilot.',
    icon: 'mail',
    iconColor: '#AF52DE',
    bullets: [
      'Drag-and-drop email builder',
      'Branded email templates with your logo',
      'Open and click tracking',
      'A/B testing for subject lines',
      'Automated triggers based on tags',
    ],
    mockup: {
      type: 'cards',
      cards: [
        { icon: 'mail', title: 'Welcome Series', sub: '3 emails · 78% open rate', color: '#34C759' },
        { icon: 'gift', title: 'Birthday Email', sub: '1 email · 92% open rate', color: '#FF9500' },
        { icon: 'car-sport', title: 'Post-Sale Drip', sub: '6 emails · 65% open rate', color: '#007AFF' },
        { icon: 'star', title: 'Review Request', sub: '2 emails · 43% click rate', color: '#C9A962' },
      ],
    },
  },
  'campaigns-dashboard': {
    title: 'Campaign Dashboard',
    subtitle: 'Campaign Analytics',
    description: 'Track every campaign in real-time. See enrollments, delivery rates, responses, and ROI at a glance.',
    icon: 'speedometer',
    iconColor: '#5AC8FA',
    bullets: [
      'Real-time enrollment and delivery tracking',
      'Response rate analytics per campaign',
      'Revenue attribution per campaign',
      'Active vs completed enrollment counts',
      'Export campaign data for reporting',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '4.7k', label: 'Active Enrollments', color: '#34C759' },
        { value: '94%', label: 'Delivery Rate', color: '#007AFF' },
        { value: '23%', label: 'Response Rate', color: '#C9A962' },
        { value: '$127k', label: 'Revenue Attributed', color: '#FF9500' },
      ],
    },
  },
  'date-triggers': {
    title: 'Date Triggers',
    subtitle: 'Automated Milestones',
    description: 'Never forget a birthday, anniversary, or holiday again. Set up once, and iMOs sends the right message at the right time — forever.',
    icon: 'calendar',
    iconColor: '#FF9500',
    bullets: [
      'Automatic birthday messages with personalization',
      'Anniversary and sold-date campaigns',
      '14+ pre-built holiday templates',
      'Custom message templates per trigger type',
      'SMS and email delivery options',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'gift', label: 'Birthday Campaign', sub: 'Active · 1,247 contacts tracked', badge: 'ON', badgeColor: '#34C759' },
        { icon: 'heart', label: 'Anniversary', sub: 'Active · 891 contacts tracked', badge: 'ON', badgeColor: '#34C759' },
        { icon: 'car-sport', label: 'Sold Date', sub: 'Active · 2,103 contacts tracked', badge: 'ON', badgeColor: '#34C759' },
        { icon: 'snow', label: 'Christmas', sub: 'Dec 25 · All contacts', badge: 'ON', badgeColor: '#34C759' },
        { icon: 'flag', label: 'Thanksgiving', sub: 'Nov 27 · All contacts', badge: 'OFF', badgeColor: '#8E8E93' },
      ],
    },
  },
  templates: {
    title: 'SMS Templates',
    subtitle: 'Quick Responses',
    description: 'Pre-built SMS templates for every situation. One tap to send a polished, on-brand message.',
    icon: 'document-text',
    iconColor: '#FFD60A',
    bullets: [
      'Pre-built templates for common scenarios',
      'Custom template creation',
      'Variable placeholders for personalization',
      'Template sharing across the team',
      'Usage analytics per template',
    ],
    mockup: {
      type: 'cards',
      cards: [
        { icon: 'hand-right', title: 'Welcome', sub: 'Hi {name}, welcome to...', color: '#34C759' },
        { icon: 'gift', title: 'Birthday', sub: 'Happy birthday {name}!', color: '#FF9500' },
        { icon: 'checkmark', title: 'Follow-up', sub: 'Just checking in...', color: '#007AFF' },
        { icon: 'star', title: 'Review Ask', sub: 'Would you mind leaving...', color: '#C9A962' },
      ],
    },
  },
  'email-templates': {
    title: 'Email Templates',
    subtitle: 'Email Designs',
    description: 'Professional email templates with your branding. Designed to convert, built to impress.',
    icon: 'mail',
    iconColor: '#34C759',
    bullets: [
      'Professionally designed email layouts',
      'Custom branding with your logo and colors',
      'Drag-and-drop editing',
      'Mobile-responsive designs',
      'Template library shared across team',
    ],
    mockup: {
      type: 'cards',
      cards: [
        { icon: 'mail', title: 'Welcome Email', sub: 'Modern, clean design', color: '#34C759' },
        { icon: 'gift', title: 'Birthday Template', sub: 'Festive with photo', color: '#FF9500' },
        { icon: 'pricetag', title: 'Promotion', sub: 'Bold, attention-grabbing', color: '#FF2D55' },
        { icon: 'ribbon', title: 'Thank You', sub: 'Elegant, personal', color: '#C9A962' },
      ],
    },
  },
  'brand-kit': {
    title: 'Brand Kit',
    subtitle: 'Email Branding',
    description: 'Your brand identity across every email. Upload your logo, set your colors, and ensure every message looks on-brand.',
    icon: 'color-palette',
    iconColor: '#AF52DE',
    bullets: [
      'Upload your company logo',
      'Set primary and secondary brand colors',
      'Custom email header and footer',
      'Consistent branding across all emails',
      'Preview before sending',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Company Logo', value: 'logo.png uploaded' },
        { label: 'Primary Color', value: '#C9A962 (Gold)' },
        { label: 'Secondary Color', value: '#1A1A1A (Dark)' },
        { label: 'Email Footer', value: 'Your Company Inc.' },
        { label: 'Social Links', value: 'Facebook, Instagram, LinkedIn' },
      ],
    },
  },
  'congrats-template': {
    title: 'Congrats Cards',
    subtitle: 'Customer Celebrations',
    description: 'Snap a photo, create a branded card, and start a lifelong relationship. Customers share these on social media — free marketing.',
    icon: 'gift',
    iconColor: '#C9A962',
    bullets: [
      'Take a photo with the customer on the spot',
      'Auto-generate branded congrats cards',
      'Customers share on social media',
      'Automatic tag and campaign enrollment',
      'Tracks social shares and engagement',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '342', label: 'Cards Created', color: '#C9A962' },
        { value: '89%', label: 'Share Rate', color: '#34C759' },
        { value: '1.2k', label: 'Social Views', color: '#007AFF' },
        { value: '67', label: 'Referrals Generated', color: '#FF9500' },
      ],
    },
  },
  analytics: {
    title: 'Analytics',
    subtitle: 'Performance Metrics',
    description: 'See how your team and campaigns are performing at a glance. Data-driven decisions made easy.',
    icon: 'stats-chart',
    iconColor: '#34C759',
    bullets: [
      'Real-time performance dashboard',
      'Message sent/received/response metrics',
      'Campaign performance tracking',
      'Team activity and productivity metrics',
      'Export data for external reporting',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '12.4k', label: 'Messages Sent', color: '#007AFF' },
        { value: '94%', label: 'Delivery Rate', color: '#34C759' },
        { value: '847', label: 'New Contacts', color: '#C9A962' },
        { value: '$89k', label: 'Revenue', color: '#FF9500' },
      ],
    },
  },
  reports: {
    title: 'Reports',
    subtitle: 'Detailed Reports',
    description: 'Deep-dive reports on every aspect of your operation. From individual performance to campaign ROI.',
    icon: 'bar-chart',
    iconColor: '#007AFF',
    bullets: [
      'Individual and team performance reports',
      'Campaign ROI and conversion tracking',
      'Customer acquisition and retention metrics',
      'Scheduled report delivery via email',
      'Custom date range filtering',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '23%', label: 'Conv. Rate', color: '#34C759' },
        { value: '4.2x', label: 'Campaign ROI', color: '#C9A962' },
        { value: '68%', label: 'Retention', color: '#007AFF' },
        { value: '-12%', label: 'Churn Rate', color: '#FF3B30' },
      ],
    },
  },
  'email-analytics': {
    title: 'Email Analytics',
    subtitle: 'Email Performance',
    description: 'Track opens, clicks, bounces, and engagement for every email sent. Optimize your messaging with data.',
    icon: 'trending-up',
    iconColor: '#FF2D55',
    bullets: [
      'Open rate tracking per email and campaign',
      'Click-through rate on links and CTAs',
      'Bounce and unsubscribe monitoring',
      'Best send time recommendations',
      'A/B test result comparisons',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '72%', label: 'Open Rate', color: '#34C759' },
        { value: '18%', label: 'Click Rate', color: '#007AFF' },
        { value: '2.1%', label: 'Bounce Rate', color: '#FF9500' },
        { value: '0.3%', label: 'Unsubscribe', color: '#FF3B30' },
      ],
    },
  },
  leaderboard: {
    title: 'Leaderboard',
    subtitle: 'Team Rankings',
    description: 'Motivate your team with real-time performance rankings. See who\'s crushing it and who needs coaching.',
    icon: 'trophy',
    iconColor: '#FFD60A',
    bullets: [
      'Real-time performance leaderboard',
      'Ranking by messages, calls, deals, and cards',
      'Daily, weekly, monthly, and all-time views',
      'Custom metrics and weighted scoring',
      'Team and individual breakdowns',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'trophy', label: '1. Sarah Johnson', sub: '247 points · 34 deals', badge: '#1', badgeColor: '#FFD60A' },
        { icon: 'medal', label: '2. Mike Davis', sub: '213 points · 28 deals', badge: '#2', badgeColor: '#C0C0C0' },
        { icon: 'medal', label: '3. Lisa Chen', sub: '198 points · 25 deals', badge: '#3', badgeColor: '#CD7F32' },
        { icon: 'person', label: '4. Robert Wilson', sub: '176 points · 21 deals', badge: '', badgeColor: '' },
        { icon: 'person', label: '5. Emma Thompson', sub: '154 points · 18 deals', badge: '', badgeColor: '' },
      ],
    },
  },
  'lead-sources': {
    title: 'Lead Sources',
    subtitle: 'Lead Routing',
    description: 'Track where your leads come from and automatically route them to the right salesperson.',
    icon: 'git-branch',
    iconColor: '#5856D6',
    bullets: [
      'Track lead source attribution',
      'Automatic lead routing rules',
      'Round-robin and priority-based assignment',
      'Source performance comparison',
      'Integration with web forms and ads',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'globe', label: 'Website Forms', sub: '342 leads this month', badge: '34%', badgeColor: '#34C759' },
        { icon: 'call', label: 'Phone Calls', sub: '187 leads this month', badge: '19%', badgeColor: '#007AFF' },
        { icon: 'people', label: 'Referrals', sub: '156 leads this month', badge: '16%', badgeColor: '#C9A962' },
        { icon: 'megaphone', label: 'Social Media', sub: '98 leads this month', badge: '10%', badgeColor: '#FF9500' },
      ],
    },
  },
  tags: {
    title: 'Contact Tags',
    subtitle: 'Tag Management',
    description: 'Organize your contacts with tags. Tags trigger campaigns, segment audiences, and power your automation.',
    icon: 'pricetags',
    iconColor: '#FF9500',
    bullets: [
      'Create and manage custom tags',
      'Tags trigger automated campaigns',
      'Bulk tag operations',
      'Tag-based contact segmentation',
      'Color-coded tag categories',
    ],
    mockup: {
      type: 'cards',
      cards: [
        { icon: 'car-sport', title: 'Sold', sub: '2,103 contacts', color: '#34C759' },
        { icon: 'star', title: 'VIP', sub: '347 contacts', color: '#C9A962' },
        { icon: 'flash', title: 'Hot Lead', sub: '89 contacts', color: '#FF3B30' },
        { icon: 'gift', title: 'Birthday Club', sub: '1,247 contacts', color: '#FF9500' },
      ],
    },
  },
  'review-links': {
    title: 'Review Links',
    subtitle: 'Online Reviews',
    description: 'Make it easy for happy customers to leave reviews. One-tap links to Google, Facebook, and Yelp.',
    icon: 'star',
    iconColor: '#FFD60A',
    bullets: [
      'Pre-configured Google, Facebook, and Yelp links',
      'One-tap review request via SMS',
      'Track review request conversion rates',
      'Automated review request campaigns',
      'Review monitoring dashboard',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'logo-google', label: 'Google Reviews', sub: '4.8 stars · 342 reviews', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'logo-facebook', label: 'Facebook', sub: '4.7 stars · 187 reviews', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'star', label: 'Yelp', sub: '4.5 stars · 98 reviews', badge: 'Setup', badgeColor: '#FF9500' },
      ],
    },
  },
  import: {
    title: 'Import Contacts',
    subtitle: 'Bulk Import',
    description: 'Import your existing contacts from CSV. Map fields, deduplicate, and get started in minutes.',
    icon: 'cloud-upload',
    iconColor: '#007AFF',
    bullets: [
      'CSV file upload with field mapping',
      'Automatic duplicate detection',
      'Tag assignment during import',
      'Import history and undo support',
      'Supports 10,000+ contacts per import',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '5.2k', label: 'Contacts Imported', color: '#34C759' },
        { value: '47', label: 'Duplicates Found', color: '#FF9500' },
        { value: '12', label: 'Fields Mapped', color: '#007AFF' },
        { value: '3', label: 'Tags Applied', color: '#C9A962' },
      ],
    },
  },
  'digital-card': {
    title: 'Digital Card',
    subtitle: 'Business Card',
    description: 'Your modern digital business card. Share your bio, contact info, socials, and more with a single link.',
    icon: 'card',
    iconColor: '#007AFF',
    bullets: [
      'Beautiful, shareable digital card',
      'Photo, bio, and social media links',
      'QR code for easy sharing',
      'Click-to-call and click-to-email',
      'View tracking and analytics',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Name', value: 'John Smith' },
        { label: 'Title', value: 'Senior Sales Consultant' },
        { label: 'Phone', value: '+1 (555) 123-4567' },
        { label: 'Email', value: 'john@company.com' },
        { label: 'Social', value: 'LinkedIn, Instagram, Facebook' },
      ],
    },
  },
  persona: {
    title: 'AI Persona',
    subtitle: 'Communication Style',
    description: 'Tell Jessi how you communicate. She\'ll match your tone, style, and personality in every suggestion.',
    icon: 'sparkles',
    iconColor: '#AF52DE',
    bullets: [
      'Set your communication style and tone',
      'Jessi adapts suggestions to match you',
      'Professional, casual, or friendly presets',
      'Custom vocabulary and phrases',
      'Continuous learning from your responses',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Communication Style', value: 'Professional & Friendly' },
        { label: 'Tone', value: 'Warm, approachable' },
        { label: 'Formality', value: 'Business casual' },
        { label: 'Sign-off', value: 'Best regards, John' },
        { label: 'Avoid', value: 'Slang, emojis in business' },
      ],
    },
  },
  jessi: {
    title: 'Ask Jessi',
    subtitle: 'AI Assistant',
    description: 'Your AI-powered assistant. Ask anything about the app, get response suggestions, or let Jessi handle routine tasks.',
    icon: 'sparkles',
    iconColor: '#C9A962',
    bullets: [
      'AI-powered response suggestions for messages',
      'Ask questions about any iMOs feature',
      'Voice-to-text note taking',
      'Smart tagging recommendations',
      'Campaign optimization suggestions',
    ],
    mockup: {
      type: 'chat',
      messages: [
        { from: 'me', text: 'How do I set up a birthday campaign?', time: '10:30 AM' },
        { from: 'them', text: 'Go to Campaigns > Date Triggers > Birthday. Enable it, write your message, and choose SMS or email. Done!', time: '10:30 AM' },
        { from: 'me', text: 'Can you suggest a birthday message?', time: '10:31 AM' },
        { from: 'them', text: 'Happy birthday, {name}! Wishing you an amazing year ahead. — Your friends at {company}', time: '10:31 AM' },
      ],
    },
  },
  account: {
    title: 'My Account',
    subtitle: 'Account Settings',
    description: 'Manage your profile, notification preferences, and account settings all in one place.',
    icon: 'person-circle',
    iconColor: '#8E8E93',
    bullets: [
      'Profile photo and personal information',
      'Notification preferences',
      'Timezone and language settings',
      'Connected accounts and sessions',
      'Account export and deletion',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Name', value: 'John Smith' },
        { label: 'Email', value: 'john@company.com' },
        { label: 'Phone', value: '+1 (555) 123-4567' },
        { label: 'Timezone', value: 'America/Denver (MST)' },
        { label: 'Notifications', value: 'Push, Email, SMS' },
      ],
    },
  },
  security: {
    title: 'Security',
    subtitle: 'Account Security',
    description: 'Keep your account safe. Manage passwords, sessions, and authentication settings.',
    icon: 'shield-checkmark',
    iconColor: '#FF3B30',
    bullets: [
      'Password management and change',
      'Two-factor authentication',
      'Active session monitoring',
      'Login history and alerts',
      'API key management',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'key', label: 'Password', sub: 'Last changed 30 days ago', badge: 'Strong', badgeColor: '#34C759' },
        { icon: 'phone-portrait', label: 'Two-Factor Auth', sub: 'Authenticator app', badge: 'ON', badgeColor: '#34C759' },
        { icon: 'laptop', label: 'Active Sessions', sub: '2 devices connected', badge: '2', badgeColor: '#007AFF' },
        { icon: 'time', label: 'Login History', sub: 'Last login: 2 hours ago', badge: '', badgeColor: '' },
      ],
    },
  },
  calendar: {
    title: 'Calendar',
    subtitle: 'Scheduling',
    description: 'Connect your calendar, schedule follow-ups, and never miss an appointment.',
    icon: 'calendar',
    iconColor: '#007AFF',
    bullets: [
      'Google Calendar and Outlook sync',
      'Schedule follow-up reminders',
      'Appointment booking from contacts',
      'Calendar view of all events',
      'Task and deadline tracking',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '8', label: 'Meetings Today', color: '#007AFF' },
        { value: '3', label: 'Follow-ups Due', color: '#FF9500' },
        { value: '12', label: 'This Week', color: '#34C759' },
        { value: '2', label: 'Overdue', color: '#FF3B30' },
      ],
    },
  },
  integrations: {
    title: 'Integrations',
    subtitle: 'Connected Services',
    description: 'Connect iMOs with your existing tools. CRM imports, calendar sync, and API access for custom workflows.',
    icon: 'git-network',
    iconColor: '#5856D6',
    bullets: [
      'Twilio for SMS and calling',
      'Google Calendar sync',
      'Resend for email delivery',
      'Webhook support for custom integrations',
      'REST API for developer access',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'chatbubble', label: 'Twilio', sub: 'SMS & Calling', badge: 'Connected', badgeColor: '#34C759' },
        { icon: 'mail', label: 'Resend', sub: 'Email delivery', badge: 'Connected', badgeColor: '#34C759' },
        { icon: 'calendar', label: 'Google Calendar', sub: 'Calendar sync', badge: 'Setup', badgeColor: '#FF9500' },
        { icon: 'code-slash', label: 'Webhooks', sub: '3 active webhooks', badge: 'Active', badgeColor: '#007AFF' },
      ],
    },
  },
  'invite-team': {
    title: 'Invite Team',
    subtitle: 'Team Management',
    description: 'Invite your team members via email. Each person gets role-based onboarding and the right level of access.',
    icon: 'person-add',
    iconColor: '#C9A962',
    bullets: [
      'Email invitations with one click',
      'Role-based access control',
      'Custom onboarding per role',
      'Invite tracking and reminders',
      'Bulk invite via CSV upload',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Email', value: 'newmember@company.com' },
        { label: 'Role', value: 'Salesperson' },
        { label: 'Store', value: 'Main Location' },
        { label: 'Team', value: 'Sales Team A' },
        { label: 'Welcome Message', value: 'Welcome to the team!' },
      ],
    },
  },
  admin: {
    title: 'Admin Dashboard',
    subtitle: 'Administration',
    description: 'Complete oversight of your organization. Manage users, stores, and monitor activity — all from one place.',
    icon: 'shield-checkmark',
    iconColor: '#34C759',
    bullets: [
      'Organization-wide activity feed',
      'User management and roles',
      'Store and team configuration',
      'System health monitoring',
      'Bulk operations and data management',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '47', label: 'Active Users', color: '#34C759' },
        { value: '5', label: 'Stores', color: '#007AFF' },
        { value: '12.4k', label: 'Messages / Month', color: '#C9A962' },
        { value: '99.9%', label: 'Uptime', color: '#34C759' },
      ],
    },
  },
  users: {
    title: 'Users',
    subtitle: 'Team Members',
    description: 'Manage every team member. Assign roles, monitor activity, and ensure everyone has the right access.',
    icon: 'people',
    iconColor: '#FF9500',
    bullets: [
      'Full user directory with search',
      'Role assignment and permissions',
      'Activity monitoring per user',
      'Deactivate or transfer contacts',
      'Performance metrics per user',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'person', label: 'Sarah Johnson', sub: 'Salesperson · Main Store', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'person', label: 'Mike Davis', sub: 'Manager · West Location', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'person', label: 'Lisa Chen', sub: 'Salesperson · Main Store', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'person', label: 'Tom Brown', sub: 'Salesperson · East Location', badge: 'Invited', badgeColor: '#FF9500' },
      ],
    },
  },
  organizations: {
    title: 'Organizations',
    subtitle: 'Org Management',
    description: 'Manage multiple organizations from a single dashboard. Perfect for enterprise deployments.',
    icon: 'business',
    iconColor: '#007AFF',
    bullets: [
      'Multi-organization hierarchy',
      'Organization-level settings and branding',
      'Cross-org reporting and analytics',
      'Centralized billing management',
      'White-label configuration per org',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'business', label: 'Acme Motors', sub: '3 stores · 24 users', badge: 'Enterprise', badgeColor: '#C9A962' },
        { icon: 'business', label: 'Smith Auto Group', sub: '5 stores · 47 users', badge: 'Enterprise', badgeColor: '#C9A962' },
        { icon: 'business', label: 'Pacific Dealers', sub: '2 stores · 12 users', badge: 'Team', badgeColor: '#007AFF' },
      ],
    },
  },
  stores: {
    title: 'Stores',
    subtitle: 'Store Management',
    description: 'Configure and manage each store location. Assign teams, set phone numbers, and track performance.',
    icon: 'storefront',
    iconColor: '#34C759',
    bullets: [
      'Store location management',
      'Team assignment per store',
      'Phone number allocation',
      'Store-level performance metrics',
      'Operating hours and details',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'storefront', label: 'Main Store', sub: '12 team members · 3 phone lines', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'storefront', label: 'West Location', sub: '8 team members · 2 phone lines', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'storefront', label: 'East Location', sub: '6 team members · 1 phone line', badge: 'New', badgeColor: '#007AFF' },
      ],
    },
  },
  'pending-users': {
    title: 'Pending Users',
    subtitle: 'Approval Queue',
    description: 'Review and approve new user signups. Control who gets access to your organization.',
    icon: 'person-add',
    iconColor: '#FF3B30',
    bullets: [
      'Review pending signup requests',
      'Approve or deny with one tap',
      'Assign role during approval',
      'Auto-assign to store and team',
      'Send welcome email on approval',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'person-add', label: 'Alex Rivera', sub: 'Applied: Salesperson · 2 hours ago', badge: 'Review', badgeColor: '#FF9500' },
        { icon: 'person-add', label: 'Casey Morgan', sub: 'Applied: Manager · 1 day ago', badge: 'Review', badgeColor: '#FF9500' },
        { icon: 'person-add', label: 'Jordan Lee', sub: 'Applied: Salesperson · 3 days ago', badge: 'Pending', badgeColor: '#8E8E93' },
      ],
    },
  },
  individuals: {
    title: 'Individuals',
    subtitle: 'Independent Users',
    description: 'Manage users who operate independently without an organization affiliation.',
    icon: 'person-circle',
    iconColor: '#AF52DE',
    bullets: [
      'Independent user management',
      'Not tied to any organization',
      'Full feature access',
      'Individual billing and settings',
      'Can be invited to organizations later',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'person', label: 'Independent Agent A', sub: 'Active since Jan 2026 · 156 contacts', badge: 'Pro', badgeColor: '#C9A962' },
        { icon: 'person', label: 'Freelance Rep B', sub: 'Active since Dec 2025 · 89 contacts', badge: 'Starter', badgeColor: '#007AFF' },
        { icon: 'person', label: 'Solo Consultant C', sub: 'Active since Feb 2026 · 34 contacts', badge: 'New', badgeColor: '#34C759' },
      ],
    },
  },
  directory: {
    title: 'Company Directory',
    subtitle: 'Team Roster',
    description: 'Your team directory with contact info, roles, and performance stats. Find anyone in seconds.',
    icon: 'people',
    iconColor: '#AF52DE',
    bullets: [
      'Searchable team directory',
      'Profile cards with contact info',
      'Role and store assignment display',
      'Quick contact actions (call, message)',
      'Performance badges and rankings',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'person', label: 'Sarah Johnson', sub: 'Sales · Main Store · #1 Rank', badge: '#1', badgeColor: '#FFD60A' },
        { icon: 'person', label: 'Mike Davis', sub: 'Manager · West Location', badge: 'Mgr', badgeColor: '#007AFF' },
        { icon: 'person', label: 'Lisa Chen', sub: 'Sales · Main Store · #3 Rank', badge: '#3', badgeColor: '#CD7F32' },
        { icon: 'person', label: 'Robert Wilson', sub: 'Sales · East Location · #4 Rank', badge: '#4', badgeColor: '#8E8E93' },
      ],
    },
  },
  'shared-inboxes': {
    title: 'Shared Inboxes',
    subtitle: 'Phone Assignments',
    description: 'Assign phone numbers to team members. Manage who can send and receive from each number.',
    icon: 'mail',
    iconColor: '#007AFF',
    bullets: [
      'Phone number assignment management',
      'Multiple numbers per team/store',
      'Shared inbox access control',
      'Message routing rules',
      'Number porting and provisioning',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'call', label: '+1 (555) 100-0001', sub: 'Main Store · Sarah, Mike, Lisa', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'call', label: '+1 (555) 100-0002', sub: 'West Location · Mike, Tom', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'call', label: '+1 (555) 100-0003', sub: 'East Location · Unassigned', badge: 'Setup', badgeColor: '#FF9500' },
      ],
    },
  },
  'bulk-transfer': {
    title: 'Bulk Transfer',
    subtitle: 'Contact Transfer',
    description: 'Transfer contacts between team members in bulk. Perfect for role changes and territory reassignment.',
    icon: 'swap-horizontal',
    iconColor: '#FF3B30',
    bullets: [
      'Transfer contacts between users',
      'Bulk selection with filters',
      'Preview before confirming',
      'Conversation history transfers with contacts',
      'Audit trail for all transfers',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: '156', label: 'Contacts Selected', color: '#007AFF' },
        { value: 'Sarah', label: 'Transfer From', color: '#FF3B30' },
        { value: 'Mike', label: 'Transfer To', color: '#34C759' },
        { value: '3', label: 'Tags Preserved', color: '#C9A962' },
      ],
    },
  },
  'phone-assignments': {
    title: 'Phone Assignments',
    subtitle: 'Twilio Numbers',
    description: 'Manage Twilio phone numbers across your organization. Assign, port, and configure numbers.',
    icon: 'call',
    iconColor: '#32ADE6',
    bullets: [
      'Twilio number management',
      'Assign numbers to users and stores',
      'Number provisioning and porting',
      'Call routing configuration',
      'Usage monitoring and billing',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'call', label: '+1 (555) 100-0001', sub: 'Assigned to: Main Store', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'call', label: '+1 (555) 100-0002', sub: 'Assigned to: West Location', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'call', label: '+1 (555) 100-0003', sub: 'Unassigned', badge: 'Available', badgeColor: '#007AFF' },
      ],
    },
  },
  'partner-agreements': {
    title: 'Partner Agreements',
    subtitle: 'Reseller Contracts',
    description: 'Manage reseller and partner agreements. Track contracts, commissions, and partnership terms.',
    icon: 'document-text',
    iconColor: '#FF9500',
    bullets: [
      'Partner agreement management',
      'Commission tracking and payouts',
      'Contract status monitoring',
      'Renewal reminders',
      'Performance metrics per partner',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'document-text', label: 'AutoTech Partners', sub: 'Commission: 15% · Active', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'document-text', label: 'DealerSolutions', sub: 'Commission: 12% · Active', badge: 'Active', badgeColor: '#34C759' },
        { icon: 'document-text', label: 'SalesForce Co', sub: 'Commission: 10% · Pending', badge: 'Pending', badgeColor: '#FF9500' },
      ],
    },
  },
  billing: {
    title: 'Billing',
    subtitle: 'Subscription & Payments',
    description: 'Manage your subscription, view invoices, and update payment methods.',
    icon: 'card',
    iconColor: '#34C759',
    bullets: [
      'Subscription plan management',
      'Invoice history and downloads',
      'Payment method management',
      'Usage-based billing details',
      'Upgrade and downgrade options',
    ],
    mockup: {
      type: 'stats',
      stats: [
        { value: 'Pro', label: 'Current Plan', color: '#C9A962' },
        { value: '$99', label: 'Monthly Cost', color: '#34C759' },
        { value: '12', label: 'Active Users', color: '#007AFF' },
        { value: 'Mar 1', label: 'Next Invoice', color: '#FF9500' },
      ],
    },
  },
  'activity-feed': {
    title: 'Activity Feed',
    subtitle: 'Recent Activity',
    description: 'See every action across your organization in real-time. Nothing falls through the cracks.',
    icon: 'pulse',
    iconColor: '#FF2D55',
    bullets: [
      'Real-time activity stream',
      'Filter by user, action type, or store',
      'Message, call, and deal tracking',
      'Campaign enrollment events',
      'Admin action audit trail',
    ],
    mockup: {
      type: 'list',
      rows: [
        { icon: 'chatbubble', label: 'Sarah sent SMS', sub: 'To Mike Davis · 2 min ago', badge: 'SMS', badgeColor: '#007AFF' },
        { icon: 'camera', label: 'Mike created card', sub: 'Congrats Card · 15 min ago', badge: 'Card', badgeColor: '#C9A962' },
        { icon: 'call', label: 'Lisa made call', sub: 'To Robert Wilson · 1 hr ago', badge: 'Call', badgeColor: '#34C759' },
        { icon: 'pricetag', label: 'Auto-tagged', sub: 'Emma Thompson → VIP · 2 hr ago', badge: 'Tag', badgeColor: '#FF9500' },
      ],
    },
  },
  training: {
    title: 'Training Hub',
    subtitle: 'Learn iMOs',
    description: 'Video tutorials, guides, and interactive training for every feature. Get your team up to speed fast.',
    icon: 'school',
    iconColor: '#FF9500',
    bullets: [
      'Step-by-step video tutorials',
      'Interactive feature walkthroughs',
      'Role-based training paths',
      'Progress tracking per user',
      'Ask Jessi for instant help',
    ],
    mockup: {
      type: 'cards',
      cards: [
        { icon: 'play-circle', title: 'Getting Started', sub: '5 videos · 12 min', color: '#34C759' },
        { icon: 'play-circle', title: 'Messaging', sub: '8 videos · 24 min', color: '#007AFF' },
        { icon: 'play-circle', title: 'Campaigns', sub: '6 videos · 18 min', color: '#FF9500' },
        { icon: 'play-circle', title: 'Admin Tools', sub: '4 videos · 10 min', color: '#AF52DE' },
      ],
    },
  },
  login: {
    title: 'Log In',
    subtitle: 'Access Your Account',
    description: 'Sign in to your iMOs account and pick up right where you left off.',
    icon: 'log-in',
    iconColor: '#007AFF',
    bullets: [
      'Secure email and password authentication',
      'Remember me for quick access',
      'Password reset via email',
      'Session management',
      'Two-factor authentication support',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Email', value: 'you@company.com' },
        { label: 'Password', value: '••••••••••••' },
        { label: 'Remember Me', value: 'Enabled' },
      ],
    },
  },
  signup: {
    title: 'Sign Up',
    subtitle: 'Create Your Account',
    description: 'Join iMOs in under 60 seconds. Free to start, no credit card required.',
    icon: 'person-add',
    iconColor: '#34C759',
    bullets: [
      'Free account creation in under 60 seconds',
      'No credit card required to start',
      'Guided onboarding for your role',
      'Instant access to all core features',
      'Upgrade anytime as you grow',
    ],
    mockup: {
      type: 'form',
      fields: [
        { label: 'Full Name', value: 'John Smith' },
        { label: 'Email', value: 'john@company.com' },
        { label: 'Password', value: '••••••••••••' },
        { label: 'Role', value: 'Salesperson' },
      ],
    },
  },
};
